### ISSUE TITLE
Crash while scanning and skipping forward

### ISSUE THREAD

**Issue by Hew-ux** [VinylMusicPlayer/VinylMusicPlayer#1024]
**Describe the bug**
The app crashes while scanning a large music collection and skipping forward tracks at the same time.

**To reproduce**
1. Have a large music collection loaded onto phone (+1000).
2. Open the app, it begins scanning.
3. Press 'shuffle all' on the track list.
4. Skip forward one song.
5. Crash.

**Expected behavior**
To not crash.

**Device info**
```
App version: 1.10.0
App version code: 197
Android build version: 1a2df0-469033
Android release version: 13
Android SDK version: 33
Android build ID: T1SUS33.1-124-6-7
Device brand: motorola
Device manufacturer: motorola
Device name: rhodep
Device model: moto g82 5G
Device product name: rhodep_gn
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/04/09 15:16:11
## Stack: 
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask$Progress.isEmpty()' on a null object reference
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.onTermination(Unknown Source:13)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.onCancelled(SourceFile:1)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.onCancelled(SourceFile:2)
	at android.os.AsyncTask.finish(AsyncTask.java:769)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8088)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
```

**Comment by Hew-ux** [comment]
Unfortunately, it still seems like the crash is present in the version that was released after this issue was closed. Here are the logs:
```
App version: 1.10.2
App version code: 199
Android build version: b53bc9-13d43
Android release version: 13
Android SDK version: 33
Android build ID: T1SUS33.1-124-6-8
Device brand: motorola
Device manufacturer: motorola
Device name: rhodep
Device model: moto g82 5G
Device product name: rhodep_gn
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/04/28 21:52:57
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.isEmpty()' on a null object reference
	at com.poupa.vinylmusicplayer.discog.MemCache.removeSongById(Unknown Source:156)
	at com.poupa.vinylmusicplayer.discog.Discography.removeSongsById(Unknown Source:29)
	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:115)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:1)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more

```

**Comment by soncaokim** [comment]
> Unfortunately, it still seems like the crash is present in the version that was released after this issue was closed. Here are the logs:
> 
> ```
> Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.isEmpty()' on a null object reference
> 	at com.poupa.vinylmusicplayer.discog.MemCache.removeSongById(Unknown Source:156)
> 	at com.poupa.vinylmusicplayer.discog.Discography.removeSongsById(Unknown Source:29)
> 	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:115)
> 	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:1)
> 	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:2)
> 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	... 4 more
> ```

Hi, this is another separate issue, linked to https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/1071
