### ISSUE TITLE
Crash Report 4/13/2024

### ISSUE THREAD

**Issue by Dr-droidz** [VinylMusicPlayer/VinylMusicPlayer#1035]
**Describe the bug**

**To reproduce**
1. Go to "Albums"
2. Press and hold down on the "phantom" albums. They are unable to be deleted or removed.
4. See error and app crashes 

**Expected behavior**
To be able to remove the "phantom" albums from my device. See attached screenshot (if it properly loading):

![Screenshot_20240414-071537](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/166996372/b08778b1-4a67-4cfa-9ec5-c3fc616ad96f)

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 App version: 1.10.0
App version code: 197
Android build version: 11445699
Android release version: 14
Android SDK version: 34
Android build ID: AP1A.240305.019.A1
Device brand: google
Device manufacturer: Google
Device name: panther
Device model: Pixel 7
Device product name: panther
Device hardware name: panther
ABIs: [arm64-v8a]
ABIs (32bit): []
ABIs (64bit): [arm64-v8a]

## Time: 
2024/04/14 07:14:06
## Stack: 
java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:ViewHolder{13a0b0d position=0 id=-1, oldPos=-1, pLpos:-1} 
 View Holder 2:ViewHolder{29f299c position=5 id=-1, oldPos=-1, pLpos:-1} com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView{2e3ff7a VFED..... ......ID 0,0-1080,1781 #7f090280 app:id/recycler_view}, adapter:com.poupa.vinylmusicplayer.adapter.album.AlbumAdapter@255972c, layout:androidx.recyclerview.widget.GridLayoutManager@547232b, context:com.poupa.vinylmusicplayer.ui.activities.MainActivity@70a7b3b
	at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(SourceFile:65)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(Unknown Source:109)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(Unknown Source:115)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at androidx.viewpager.widget.ViewPager.onLayout(Unknown Source:258)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(Unknown Source:135)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(Unknown Source:0)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(Unknown Source:42)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onLayout(Unknown Source:145)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(Unknown Source:56)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:807)
	at android.view.View.layout(View.java:24722)
	at android.view.ViewGroup.layout(ViewGroup.java:6450)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4485)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3786)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2659)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9789)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1399)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1408)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1008)
	at android.view.Choreographer.doFrame(Choreographer.java:938)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1382)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)

**Additional context**

Unrelated (I think) to the "phantom" albums, but sometimes when attempting to play a track from the widget on the phone's home screen, it says "Can not play this song" and completely forgets the album or song that been played previously. This happens in the app too once you open it after the initial error with the home screen widget and nothing is playing on the app. Before the most recent update,.this was not much of an issue. I am unable to recreate it now, but if I do manage to, I will send another error support ticket on here. Thank you for creating a great successor to Phonograph and have a great day.

**Comment by sin-ack** [comment]
Also experiencing the phantom albums with recent releases, anyone know why?

**Comment by lhardt** [comment]
Seems to be the same issue as #1109 , as this is a ViewHolder with ID `-1` in the `AlbumAdapter`.
