### ISSUE TITLE
Crash during import

### ISSUE THREAD

**Issue by fekir** [VinylMusicPlayer/VinylMusicPlayer#1037]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**

**Comment by fekir** [comment]
2024/04/16 06:48:56
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set java.util.Map.entrySet()' on a null object reference
	at com.poupa.vinylmusicplayer.discog.MemCache.removeSongById(Unknown Source:34)
	at com.poupa.vinylmusicplayer.discog.Discography.removeSongById(Unknown Source:16)
	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:124)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:1)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
