### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by UnixParadigm** [VinylMusicPlayer/VinylMusicPlayer#1044]
**Describe the bug**
Your guess is as good as mine. Some issue with clearing a song by ID from cache? Im not a Java dev, I have no clue.

**To reproduce**
1. Open Vinyl Music Player
2. ???????
3. See error

**Expected behavior**
Vinyl does not crash on startup.

**Device info**
App version: 1.10.0
App version code: 197
Android build version: 2024040900
Android release version: 14
Android SDK version: 34
Android build ID: 2024040900
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven
Device hardware name: raven
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/04/22 14:12:16
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set java.util.Map.entrySet()' on a null object reference
	at com.poupa.vinylmusicplayer.discog.MemCache.removeSongById(Unknown Source:34)
	at com.poupa.vinylmusicplayer.discog.Discography.removeSongById(Unknown Source:16)
	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:124)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:1)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more

**Additional context**
I can bypass the crash by tapping outside the error prompt and the app functions fine. I cannot add m3u playlists however. I scan them and then attempt to add them and Vinyl reports they are not scanned. Not sure if relevant.

**Comment by UnixParadigm** [comment]
Updated to 1.10.1 which unfortunely did not fix this soft crash.

Crash report follows:

App version: 1.10.1
App version code: 198
Android build version: 2024042100
Android release version: 14
Android SDK version: 34
Android build ID: 2024042100
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven
Device hardware name: raven
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/05/01 18:05:42
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.isEmpty()' on a null object reference
	at com.poupa.vinylmusicplayer.discog.MemCache.removeSongById(Unknown Source:156)
	at com.poupa.vinylmusicplayer.discog.Discography.removeSongsById(Unknown Source:29)
	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:115)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:1)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more

 - Device: Pixel 6 Pro
 - Android Version: 14
 - ROM: GrapheneOS
 - Vinyl Music Player Version: 1.10.1

Please let me know if theres anything else you'd like to know.
