### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Nostronoe** [VinylMusicPlayer/VinylMusicPlayer#1052]
**Describe the bug**

App version: 1.10.0
App version code: 197
Android build version: A225MUBS7CXD1
Android release version: 13
Android SDK version: 33
Android build ID: TP1A.220624.014.A225MUBS7CXD1
Device brand: samsung
Device manufacturer: samsung
Device name: a22
Device model: SM-A225M
Device product name: a22ub
Device hardware name: mt6769t
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/04/23 14:52:31
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Set java.util.Map.entrySet()' on a null object reference
	at com.poupa.vinylmusicplayer.discog.MemCache.removeSongById(Unknown Source:34)
	at com.poupa.vinylmusicplayer.discog.Discography.removeSongById(Unknown Source:16)
	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:124)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:1)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more

**To reproduce**

**Expected behavior**

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**

**Comment by soncaokim** [comment]
Fixer by #1045
