### ISSUE TITLE
The latest update (V.1.10.1) produced a constant bug

### ISSUE THREAD

**Issue by Claudius8** [VinylMusicPlayer/VinylMusicPlayer#1071]
![Screenshot_20240504-082516_Trebuchet](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/168535729/97581a0f-73d1-4844-8c13-7bf67c3aa152)
**Describe the bug**
The bug happens immediately after launching Vinyl and the crash reports appears after one second. Shortly after Vinyl closes down.

**To reproduce**
1. start Vinyl

**Expected behavior**
No crash

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Lineage Version: 19-20230414-NIGHTLY-beyond1lte
 - ROM: Lineage 19
 - Vinyl Music Player Version: 1.10.1

**Additional context**
My smart phone runs on lineage. Vinyl never had any bugs before.

**Comment by soncaokim** [comment]
Is it possible to copy and paste the crash report (stack trace) here, so that I can have a better understanding of the issue?

**Comment by Claudius8** [comment]
Ironically Vinyl doesn't crash anymore as I tried to send the report. I may wait for a week or so and close the issue if no error occurs.
Best regards

Am 6. Mai 2024 09:33:10 MESZ schrieb soncaokim ***@***.***>:

**Comment by Claudius8** [comment]
App version: 1.10.2
App version code: 199
Android build version: 00c39c02b6
Android release version: 12
Android SDK version: 32
Android build ID: lineage_beyond1lte-userdebug 12 SQ3A.220705.004 00c39c02b6
Device brand: samsung
Device manufacturer: samsung
Device name: beyond1lte
Device model: SM-G973F
Device product name: lineage_beyond1lte
Device hardware name: exynos9820
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/05/07 12:44:55
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.isEmpty()' on a null object reference
	at com.poupa.vinylmusicplayer.discog.MemCache.removeSongById(Unknown Source:156)
	at com.poupa.vinylmusicplayer.discog.Discography.removeSongsById(Unknown Source:29)
	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:115)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:1)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
