### ISSUE TITLE
Error on opening (background job?)

### ISSUE THREAD

**Issue by WoM4bLEjR** [VinylMusicPlayer/VinylMusicPlayer#1081]
**Describe the bug**
App opened and switched to tab 'songs' >>> error :/

**log**
App version: 1.10.3
App version code: 200
Android build version: LTE_D0201121.0_S61_1.028.00
Android release version: 9
Android SDK version: 28
Android build ID: LTE_D0201121.0_S61_1.028.00
Device brand: Cat
Device manufacturer: BullittGroupLimited
Device name: CatS61
Device model: S61
Device product name: CatS61
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/05/10 23:22:45
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.isEmpty()' on a null object reference
	at com.poupa.vinylmusicplayer.discog.MemCache.removeSongById(Unknown Source:156)
	at com.poupa.vinylmusicplayer.discog.Discography.removeSongsById(Unknown Source:29)
	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:115)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:1)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by soncaokim** [comment]
Fixed by #1079
