### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by TheCrowned** [VinylMusicPlayer/VinylMusicPlayer#1082]
App version: 1.10.1
App version code: 198
Android build version: 14
Android release version: 10
Android SDK version: 29
Android build ID: QQ2A.200501.001.B2 release-keys
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus6
Device model: ONEPLUS A6003
Device product name: OnePlus6
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/05/11 20:10:08
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:399)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.isEmpty()' on a null object reference
	at com.poupa.vinylmusicplayer.discog.MemCache.removeSongById(Unknown Source:156)
	at com.poupa.vinylmusicplayer.discog.Discography.removeSongsById(Unknown Source:29)
	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:115)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:1)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by soncaokim** [comment]
Fixed by #1079
