### ISSUE TITLE
Unable to open the app

### ISSUE THREAD

**Issue by bobeeeze** [VinylMusicPlayer/VinylMusicPlayer#1089]
**Describe the bug**
Sinceramente a couple of weeks the app can't start

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

App version: 1.10.3
App version code: 200
Android build version: V816.0.1.0.TGKEUXM
Android release version: 13
Android SDK version: 33
Android build ID: TKQ1.221114.001 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: spesn
Device model: 2201117TY
Device product name: spesn_eea
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/05/19 12:05:20
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.isEmpty()' on a null object reference
	at com.poupa.vinylmusicplayer.discog.MemCache.removeSongById(Unknown Source:156)
	at com.poupa.vinylmusicplayer.discog.Discography.removeSongsById(Unknown Source:29)
	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:115)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:1)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more

**Comment by lhardt** [comment]
This seems to have been solved on the latest release: 

See the [changelog]((https://github.com/VinylMusicPlayer/VinylMusicPlayer/releases) : 
> Fix crasher - when the device just started and the storage/mediastore is not ready by @soncaokim in https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/1087
