### ISSUE TITLE
Delete unknown albums in Vinyl

### ISSUE THREAD

**Issue by brudolge** [VinylMusicPlayer/VinylMusicPlayer#1109]
**Describe the bug**

When I start the app, I have a few "unknown albums" in which there are no tracks. If I press on them longer to delete them, the app crashes.

**To reproduce**

Restart

***
App version: 1.10.4
App version code: 201
Android build version: 2024071200
Android release version: 14
Android SDK version: 34
Android build ID: 2024071200
Device brand: google
Device manufacturer: Google
Device name: husky
Device model: Pixel 8 Pro
Device product name: husky
Device hardware name: husky
ABIs: [arm64-v8a]
ABIs (32bit): []
ABIs (64bit): [arm64-v8a]

## Time: 
2024/07/17 19:49:12
## Stack: 
java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:ViewHolder{d6f2fad position=0 id=-1, oldPos=-1, pLpos:-1} 
 View Holder 2:ViewHolder{994fe60 position=1 id=-1, oldPos=-1, pLpos:-1} com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView{fc37854 VFED..... ......ID 0,0-1008,1717 #7f090280 app:id/recycler_view}, adapter:com.poupa.vinylmusicplayer.adapter.album.AlbumAdapter@16d35fe, layout:androidx.recyclerview.widget.GridLayoutManager@9dc03fd, context:com.poupa.vinylmusicplayer.ui.activities.MainActivity@144f42b
	at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(SourceFile:65)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(Unknown Source:109)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(Unknown Source:115)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at androidx.viewpager.widget.ViewPager.onLayout(Unknown Source:258)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(Unknown Source:135)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(Unknown Source:0)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(Unknown Source:42)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onLayout(Unknown Source:145)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(Unknown Source:56)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:807)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4562)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3830)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2718)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9937)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)

**Comment by locusus** [comment]
**Describe the bug**
Selecting an empty album (longpressing) hard crashes application.
**To reproduce**
Steps to reproduce the behavior:
1. Go to Albums tab
2. Long press empty album

**Expected behavior**
I figure the album will be selected and give context menu options to remove or hide an empty album.

**Device info**
App version: 1.10.4
App version code: 201
Android build version: 2024072800
Android release version: 14
Android SDK version: 34
Android build ID: 2024072800
Device brand: google
Device manufacturer: Google
Device name: barbet
Device model: Pixel 5a
Device product name: barbet
Device hardware name: barbet
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/08/01 14:16:56
## Stack: 
java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:ViewHolder{533cfb1 position=0 id=-1, oldPos=-1, pLpos:-1} 
 View Holder 2:ViewHolder{e27ca63 position=3 id=-1, oldPos=-1, pLpos:-1} com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView{78c9083 VFED..... ......ID 0,0-1080,1718 #7f090280 app:id/recycler_view}, adapter:com.poupa.vinylmusicplayer.adapter.album.AlbumAdapter@4582a39, layout:androidx.recyclerview.widget.GridLayoutManager@edabc74, context:com.poupa.vinylmusicplayer.ui.activities.MainActivity@861c93d
	at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(SourceFile:65)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(Unknown Source:109)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(Unknown Source:115)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at androidx.viewpager.widget.ViewPager.onLayout(Unknown Source:258)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(Unknown Source:135)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(Unknown Source:0)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(Unknown Source:0)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(Unknown Source:42)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onLayout(Unknown Source:145)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(Unknown Source:56)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:807)
	at android.view.View.layout(View.java:25159)
	at android.view.ViewGroup.layout(ViewGroup.java:6460)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4562)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3830)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2718)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9937)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)

**Comment by lhardt** [comment]
I have many empty "Unknown Album"s on my device as well, and they crash just as described above. 

I guess there is never a check for 'dangling albums'  outside of `MemCache.removeSongById`, but it could help clean up unkown ones.  Is this repo accepting code contributions?

**Comment by lhardt** [comment]
I am currently working to fix this.

It seems an issue with processing albums with no artists on `albumsByAlbumIdAndArtistId`.

`Discography.getAllAlbums` does not check if there are album with no artists (ie. one key in `albumsByAlbumIdAndArtistId` with 0 elements).   Then, `mergeFullAlbum` returns just a plain `new Album()`. Hence many albums with `id=-1`.

I will create a PR for that soon.
