### ISSUE TITLE
Crash not at launch but on play 

### ISSUE THREAD

**Issue by Fandor55** [VinylMusicPlayer/VinylMusicPlayer#1157]
App version: 1.11.0
App version code: 202
Android build version: V816.0.5.0.TGKEUXM
Android release version: 13
Android SDK version: 33
Android build ID: TKQ1.221114.001 test-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: spesn
Device model: 2201117TY
Device product name: spesn_eea
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/12/20 20:04:20
## Stack: 
java.lang.IllegalStateException: Couldn't read row 794, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:539)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:78)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.updateExistingRow(Unknown Source:6)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.updateResults(Unknown Source:54)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.<init>(Unknown Source:18)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.getInstance(Unknown Source:13)
	at com.poupa.vinylmusicplayer.service.MusicService.handleChangeInternal(Unknown Source:109)
	at com.poupa.vinylmusicplayer.service.MusicService.play(Unknown Source:59)
	at com.poupa.vinylmusicplayer.helper.MusicPlayerRemote.resumePlaying(Unknown Source:4)
	at com.poupa.vinylmusicplayer.helper.PlayPauseButtonOnClickHandler.onClick(Unknown Source:10)
	at android.view.View.performClick(View.java:7600)
	at android.view.View.performClickInternal(View.java:7577)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30186)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by lhardt** [comment]
This seems to be the same bug found on #1088, and on the exact same row `794`. 
Notice also the users have a different version of the app. 

This might be due to the large number of columns in the table exceeding the Cursor maximum size. 
See, for example: https://github.com/nextcloud/android/issues/9948

This was also noticed (and a workaround was provided) on #1120
