### ISSUE TITLE
Crash when scrolling through a playlist

### ISSUE THREAD

**Issue by zethra** [VinylMusicPlayer/VinylMusicPlayer#628]
**Describe the bug**
If you scroll, starting at the top of a playlist, using the scroll bar, the app crashes.

**To Reproduce**
1. Open a playlist
2. Scroll down using the scroll bar
3. App crashes

**Expected behavior**
No crash

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - Android Version: Android 13
 - ROM: CalyxOS
 - Vinyl Music Player Version: 1.3.0

**Additional context**

Crash only happens whe scrolling from the top of a playlist and using the scroll bar.

```
FATAL EXCEPTION: main
Process: com.poupa.vinylmusicplayer, PID: 20955
java.lang.ClassCastException: com.poupa.vinylmusicplayer.adapter.song.AbsOffsetSongAdapter$ViewHolder cannot be cast to com.poupa.vinylmusicplayer.adapter.song.OrderablePlaylistSongAdapter$ViewHolder
	at com.poupa.vinylmusicplayer.adapter.song.OrderablePlaylistSongAdapter.onCheckCanStartDrag(Unknown Source:0)
	at com.h6ah4i.android.widget.advrecyclerview.draggable.DraggableItemWrapperAdapter.canStartDrag(Unknown Source:12)
	at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.canStartDrag(Unknown Source:52)
	at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.handleActionDown(Unknown Source:34)
	at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager.onInterceptTouchEvent(Unknown Source:44)
	at com.h6ah4i.android.widget.advrecyclerview.draggable.RecyclerViewDragDropManager$1.onInterceptTouchEvent(Unknown Source:2)
	at androidx.recyclerview.widget.RecyclerView.findInterceptingOnItemTouchListener(Unknown Source:22)
	at androidx.recyclerview.widget.RecyclerView.onInterceptTouchEvent(Unknown Source:9)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2653)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchTouchEvent(Unknown Source:197)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2745)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:498)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1899)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4262)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(Unknown Source:2)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(Unknown Source:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:456)
	at android.view.View.dispatchPointerEvent(View.java:15263)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6548)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6348)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5804)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5861)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5827)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5992)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5835)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6049)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5808)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5861)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5827)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5835)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5808)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8857)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8808)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8777)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8980)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:335)
	at android.os.Looper.loopOnce(Looper.java:161)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7898)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by soncaokim** [comment]
Hello, is this still a problem with a newer version of the app (ie 1.4.0 or 1.4.1)?

**Comment by zethra** [comment]
It seems to be fixed now!
