### ISSUE TITLE
Crash while removing multiples played songs in playing queue

### ISSUE THREAD

**Issue by soncaokim** [VinylMusicPlayer/VinylMusicPlayer#667]
Impossible to relaunch the app again (the queue is possibly corrupt) - see #668 

App version: 1.4.1-cont-integ_ca11040d_230131-0128 CI
App version code: 179
Android build version: 17632250b8
Android release version: 13
Android SDK version: 33
Android build ID: lineage_cheeseburger-userdebug 13 TQ1A.230105.001.A2 17632250b8
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus5
Device model: ONEPLUS A5000
Device product name: OnePlus5
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Tue Jan 31 09:21:33 GMT+01:00 2023

Stack:
```
java.lang.IllegalArgumentException: Bad index=-1
	at com.poupa.vinylmusicplayer.misc.queue.StaticPlayingQueue.updateQueueIndexesAfterSongsModification(SourceFile:84)
	at com.poupa.vinylmusicplayer.misc.queue.StaticPlayingQueue.remove(Unknown Source:19)
	at com.poupa.vinylmusicplayer.service.MusicService.removeSong(Unknown Source:18)
	at com.poupa.vinylmusicplayer.helper.MusicPlayerRemote.removeFromQueue(Unknown Source:18)
	at com.poupa.vinylmusicplayer.adapter.song.PlayingQueueAdapter$SwipedResultActionRemoveItem.onSlideAnimationEnd(Unknown Source:26)
	at com.h6ah4i.android.widget.advrecyclerview.swipeable.action.SwipeResultAction.slideAnimationEnd(Unknown Source:0)
	at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator$SlidingAnimatorListenerObject.onAnimationEnd(Unknown Source:49)
	at androidx.core.view.ViewPropertyAnimatorCompat$1.onAnimationEnd(Unknown Source:4)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1115)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1333)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1575)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:307)
	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by soncaokim** [comment]
Closing this, it's not happenning personally to me any more
