### ISSUE TITLE
Crash add to new playlist

### ISSUE THREAD

**Issue by soncaokim** [VinylMusicPlayer/VinylMusicPlayer#676]
App version: 1.4.1-cont-integ_c8ab695f_230202-1438 CI
App version code: 179
Android build version: 17632250b8
Android release version: 13
Android SDK version: 33
Android build ID: lineage_cheeseburger-userdebug 13 TQ1A.230105.001.A2 17632250b8
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus5
Device model: ONEPLUS A5000
Device product name: OnePlus5
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Fri Feb 03 21:28:42 GMT+01:00 2023

Stack:
```
java.lang.IllegalArgumentException: Invalid token Priority
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1219)
	at android.content.ContentResolver.query(ContentResolver.java:1151)
	at android.content.ContentResolver.query(ContentResolver.java:1107)
	at com.poupa.vinylmusicplayer.util.PlaylistsUtil.doesPlaylistExistImpl(Unknown Source:12)
	at com.poupa.vinylmusicplayer.util.PlaylistsUtil.doesPlaylistExist(SourceFile:8)
	at com.poupa.vinylmusicplayer.dialogs.CreatePlaylistDialog.lambda$onCreateDialog$0(Unknown Source:25)
	at com.poupa.vinylmusicplayer.dialogs.CreatePlaylistDialog.a(Unknown Source:0)
	at androidx.constraintlayout.core.state.a.onInput(Unknown Source:10)
	at com.afollestad.materialdialogs.MaterialDialog.onClick(Unknown Source:86)
	at android.view.View.performClick(View.java:7506)
	at android.view.View.performClickInternal(View.java:7483)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:29341)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

```

**Comment by soncaokim** [comment]
Linked to changes introduced in https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/672/files
