### ISSUE TITLE
internal-playlists: Crash

### ISSUE THREAD

**Issue by soncaokim** [VinylMusicPlayer/VinylMusicPlayer#704]
**This crash concerns the 'internal-playlist' branch, i e. Not in production code**

App version: 1.5.0-cont-integ_e66a9ccc_230222-1738 CI
App version code: 180
Android build version: db68469a7b
Android release version: 13
Android SDK version: 33
Android build ID: lineage_cheeseburger-userdebug 13 TQ1A.230205.002 db68469a7b
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus5
Device model: ONEPLUS A5000
Device product name: OnePlus5
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Thu Feb 23 04:21:26 GMT+01:00 2023

Stack:
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at androidx.loader.content.ModernAsyncTask$3.done(Unknown Source:33)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes()' on a null object reference
	at com.poupa.vinylmusicplayer.provider.StaticPlaylist.asPlaylist(Unknown Source:4)
	at com.poupa.vinylmusicplayer.ui.fragments.mainactivity.library.pager.PlaylistsFragment$AsyncPlaylistLoader.getAllPlaylists(Unknown Source:93)
	at com.poupa.vinylmusicplayer.ui.fragments.mainactivity.library.pager.PlaylistsFragment$AsyncPlaylistLoader.loadInBackground(Unknown Source:4)
	at com.poupa.vinylmusicplayer.ui.fragments.mainactivity.library.pager.PlaylistsFragment$AsyncPlaylistLoader.loadInBackground(Unknown Source:0)
	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(Unknown Source:0)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(Unknown Source:2)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(Unknown Source:2)
	at androidx.loader.content.ModernAsyncTask$2.call(Unknown Source:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more

```

**Comment by soncaokim** [comment]
Fixed by https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/492/commits/73b4a2e1db255562fe08717aa64a177a0529b804
