### ISSUE TITLE
Vinyl crash on library scan (or on initial launch / fresh install)

### ISSUE THREAD

**Issue by ElSamhaa** [VinylMusicPlayer/VinylMusicPlayer#707]
App version: 1.5.0-HEAD_938378d_230220-1609 CI
App version code: 180
Android build version: V13.0.16.0.SKFMIXM
Android release version: 12
Android SDK version: 31
Android build ID: SKQ1.210908.001 release-keys
Device brand: Redmi
Device manufacturer: Xiaomi
Device name: sweet
Device model: M2101K6G
Device product name: sweet_global
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Fri Feb 24 17:13:00 GMT+03:00 2023

Stack:
java.lang.IllegalStateException: Can't access ViewModels from detached fragment
	at androidx.fragment.app.Fragment.getViewModelStore(Unknown Source:35)
	at androidx.loader.app.LoaderManager.getInstance(Unknown Source:5)
	at com.poupa.vinylmusicplayer.ui.fragments.mainactivity.library.pager.SongsFragment.reload(Unknown Source:0)
	at com.poupa.vinylmusicplayer.discog.a.accept(Unknown Source:20)
	at com.poupa.vinylmusicplayer.helper.WeakMethodReference.run(Unknown Source:10)
	at android.os.Handler.handleCallback(Unknown Source:2)
	at android.os.Handler.dispatchMessage(Unknown Source:4)
	at android.os.Looper.loopOnce(Unknown Source:176)
	at android.os.Looper.loop(Unknown Source:77)
	at android.app.ActivityThread.main(Unknown Source:155)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
	at com.android.internal.os.ZygoteInit.main(Unknown Source:306)

**Comment by soncaokim** [comment]
Can you give more information on the context of the crash? What you were doing/trying to do with the app when it crashed?

Thanks

**Comment by ElSamhaa** [comment]
@soncaokim I think I was just opening the app for the first time after the update. Strangely though, it might be worth mentioning that the old version was installed from F-droid, while the latest version I got from github releases.

On a side note, the app silently crashes with not warnings or anything. I have it configured to auto-start and battery optimizations are turned off.

**Comment by soncaokim** [comment]
Reopen this, still happening with the latest master (as of Oct 28)
