### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Verhoeckx** [VinylMusicPlayer/VinylMusicPlayer#716]
App version: 1.5
App version code: 180
Android build version: SP1Y
Android release version: 12
Android SDK version: 31
Android build ID: FP4.SP1Y.B.041.20230109
Device brand: Fairphone
Device manufacturer: Fairphone
Device name: FP4
Device model: FP4
Device product name: FP4eea
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Sun Mar 05 11:19:54 GMT+01:00 2023

Stack:
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at com.poupa.vinylmusicplayer.dialogs.BottomSheetDialog.BottomSheetDialogWithButtons.onCreateView(Unknown Source:25)
	at androidx.fragment.app.Fragment.performCreateView(Unknown Source:19)
	at androidx.fragment.app.DialogFragment.performCreateView(Unknown Source:0)
	at androidx.fragment.app.FragmentStateManager.createView(Unknown Source:189)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(Unknown Source:121)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(Unknown Source:30)
	at androidx.fragment.app.FragmentManager.moveToState(Unknown Source:27)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(Unknown Source:9)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(Unknown Source:11)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(Unknown Source:4)
	at androidx.fragment.app.FragmentActivity.onStart(Unknown Source:20)
	at androidx.appcompat.app.AppCompatActivity.onStart(Unknown Source:0)
	at com.poupa.vinylmusicplayer.ui.activities.base.AbsSlidingMusicPanelActivity.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1456)
	at android.app.Activity.performStart(Activity.java:8075)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3661)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2211)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7894)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

**Comment by soncaokim** [comment]
Cancel, the issue https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/727 is similar and providing more information
