### ISSUE TITLE
Title card rendered while screen orientation occurs causes a crash 

### ISSUE THREAD

**Issue by User2564** [VinylMusicPlayer/VinylMusicPlayer#727]
**To reproduce**
1. Go to 'Songs' tab.
2. Tap on an entry. E.g.  listing "About to add 14035 titles into the playing queue. How do you want to proceed with these songs? Play - Play Next - Add to playing queue" - which locally translates to ((I Can't get No) Satisfaction), 2 - Devo . Q: Are We Not Men? A: We Are Devo!
3. Rotate device such that the orientation changes.

**Expected behavior**
After a slight delay, the screen to continue to render without crashing.

**Device info**
[Portrait  to Landscape]
App version: 1.5.0
App version code: 180
Android build version: compiler01131555
Android release version: 12
Android SDK version: 31
Android build ID: SP1A.210812.003 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: 2023
Device model: V2023
Device product name: 2023E
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Sun Mar 19 19:09:34 GMT+13:00 2023

Stack:
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at com.poupa.vinylmusicplayer.dialogs.BottomSheetDialog.BottomSheetDialogWithButtons.onCreateView(Unknown Source:25)
	at androidx.fragment.app.Fragment.performCreateView(Unknown Source:19)
	at androidx.fragment.app.DialogFragment.performCreateView(Unknown Source:0)
	at androidx.fragment.app.FragmentStateManager.createView(Unknown Source:189)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(Unknown Source:121)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(Unknown Source:30)
	at androidx.fragment.app.FragmentManager.moveToState(Unknown Source:27)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(Unknown Source:9)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(Unknown Source:11)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(Unknown Source:4)
	at androidx.fragment.app.FragmentActivity.onStart(Unknown Source:20)
	at androidx.appcompat.app.AppCompatActivity.onStart(Unknown Source:0)
	at com.poupa.vinylmusicplayer.ui.activities.base.AbsSlidingMusicPanelActivity.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1505)
	at android.app.Activity.performStart(Activity.java:8394)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3964)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2441)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

[Landscape to Portrait]
App version: 1.5.0
App version code: 180
Android build version: compiler01131555
Android release version: 12
Android SDK version: 31
Android build ID: SP1A.210812.003 release-keys
Device brand: vivo
Device manufacturer: vivo
Device name: 2023
Device model: V2023
Device product name: 2023E
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Sun Mar 19 19:11:10 GMT+13:00 2023

Stack:
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at com.poupa.vinylmusicplayer.dialogs.BottomSheetDialog.BottomSheetDialogWithButtons.onCreateView(Unknown Source:25)
	at androidx.fragment.app.Fragment.performCreateView(Unknown Source:19)
	at androidx.fragment.app.DialogFragment.performCreateView(Unknown Source:0)
	at androidx.fragment.app.FragmentStateManager.createView(Unknown Source:189)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(Unknown Source:121)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(Unknown Source:30)
	at androidx.fragment.app.FragmentManager.moveToState(Unknown Source:27)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(Unknown Source:9)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(Unknown Source:11)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(Unknown Source:4)
	at androidx.fragment.app.FragmentActivity.onStart(Unknown Source:20)
	at androidx.appcompat.app.AppCompatActivity.onStart(Unknown Source:0)
	at com.poupa.vinylmusicplayer.ui.activities.base.AbsSlidingMusicPanelActivity.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1505)
	at android.app.Activity.performStart(Activity.java:8394)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3964)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2441)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)

**Comment by soncaokim** [comment]
Closing this, assume as fixed by https://github.com/VinylMusicPlayer/VinylMusicPlayer/pull/765
