### ISSUE TITLE
App crashed after device rotation with open popup message

### ISSUE THREAD

**Issue by DO1JLR** [VinylMusicPlayer/VinylMusicPlayer#737]
**Describe the bug**

**To reproduce**
1. Go to 'Alben' in Landscape orientation
2. Click on an Album and the first Title
3. The Popup 'About to Add 59 titles into the playing queue. How do you want to procede with these Songs' appears, but only the headliine and not the options are visible because oft the landscape orientation of the phone and the popup does not scroll.
4. Rotate Phone from landscape to Portrait.
5. See error

**Device info**

```
ROM: GrapheneOS
App version: 1.5.0
App version code: 180
Android build version: 2023041100
Android release version: 13
Android SDK version: 33
Android build ID: TQ2A.230405.003.E1.2023041100
Device brand: google
Device manufacturer: Google
Device name: raven
Device model: Pixel 6 Pro
Device product name: raven
Device hardware name: raven
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Sat Apr 15 09:20:21 GMT+02:00 2023

Stack:
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
	at com.poupa.vinylmusicplayer.dialogs.BottomSheetDialog.BottomSheetDialogWithButtons.onCreateView(Unknown Source:25)
	at androidx.fragment.app.Fragment.performCreateView(Unknown Source:19)
	at androidx.fragment.app.DialogFragment.performCreateView(Unknown Source:0)
	at androidx.fragment.app.FragmentStateManager.createView(Unknown Source:189)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(Unknown Source:121)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(Unknown Source:30)
	at androidx.fragment.app.FragmentManager.moveToState(Unknown Source:27)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(Unknown Source:9)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(Unknown Source:11)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(Unknown Source:4)
	at androidx.fragment.app.FragmentActivity.onStart(Unknown Source:20)
	at androidx.appcompat.app.AppCompatActivity.onStart(Unknown Source:0)
	at com.poupa.vinylmusicplayer.ui.activities.base.AbsSlidingMusicPanelActivity.onStart(Unknown Source:0)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1548)
	at android.app.Activity.performStart(Activity.java:8413)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3667)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2304)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7891)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

 
**Additional context**

Popup message unable to scroll and crash when rotating the phone:
![Screenshot_20230415-093721](https://user-images.githubusercontent.com/16953664/232196415-56aa256c-abde-4fb8-b98c-99262672f6bc.png)

Popup message is working without error in portrait:
![Screenshot_20230415-092746](https://user-images.githubusercontent.com/16953664/232196316-868451c0-99fe-462c-a53d-949e6057ced7.png)

**Comment by Osiris-Team** [comment]
@DO1JLR Unable to reproduce this.

What I did:
1. Go to 'Alben' in Landscape orientation
1. Click on an Album and the first Title
1. The Popup 'About to Add 59 titles into the playing queue. How do you want to procede with these Songs' appears, but only the headliine and not the options are visible because oft the landscape orientation of the phone and the popup does not scroll.
Rotate Phone from landscape to Portrait. **(NOTE: I don't get this warning/popup)**
1. See error **(NOTE: No error)**

**Comment by DO1JLR** [comment]
Yes, looks like the error is gone. thanks :kissing_heart:

**Comment by DO1JLR** [comment]
My guess is, from version ``1.5.0`` to ``1.5.2`` the popup disappeared. And without the popup there is no more error :sweat_smile:

**Comment by soncaokim** [comment]
Hmm, thanks to be active on this. Though I cannot reproduce the error, there is no change intended for this in recent 1.5.2 version.

You should have the popup if the setting " default action on choosing/tapping a song" is set to "always ask"

**Comment by DO1JLR** [comment]
Yes, good point. I change it in the settings and the popup is back.

but the error after after device rotation is gone. Thanks. Awesome App btw.
