### ISSUE TITLE
StringIndexOutOfBoundsException in com.poupa.vinylmusicplayer.sort.Utils.getSectionName

### ISSUE THREAD

**Issue by rednotmad** [VinylMusicPlayer/VinylMusicPlayer#750]
# Description
A StringIndexOutOfBoundsException happen in com.poupa.vinylmusicplayer.sort.Utils.getSectionName and cause a crash just after launch. (It seems to happen with a empty section name.)

# Device info

App version: 1.5.0
App version code: 180
Android build version: a4458-cd874
Android release version: 12
Android SDK version: 31
Android build ID: S1RFS32.27-25-11-9
Device brand: motorola
Device manufacturer: motorola
Device name: ibiza
Device model: moto g(50)
Device product name: ibiza_retaile
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

# Additional context

```
Time: Sat Jun 24 18:31:39 GMT+02:00 2023

Stack:
java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at java.lang.String.charAt(Native Method)
	at com.poupa.vinylmusicplayer.sort.Utils.getSectionName(Unknown Source:1)
	at com.poupa.vinylmusicplayer.sort.AlbumSortOrder.lambda$static$2(Unknown Source:4)
	at com.poupa.vinylmusicplayer.sort.AlbumSortOrder.g(Unknown Source:0)
	at com.poupa.vinylmusicplayer.dialogs.g.apply(Unknown Source:156)
	at com.poupa.vinylmusicplayer.adapter.album.AlbumAdapter.getSectionName(Unknown Source:22)
	at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.scrollToPositionAtProgress(Unknown Source:113)
	at com.simplecityapps.recyclerview_fastscroll.views.FastScroller.handleTouchEvent(Unknown Source:114)
	at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.handleTouchEvent(Unknown Source:40)
	at com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView.onInterceptTouchEvent(Unknown Source:0)
	at androidx.recyclerview.widget.RecyclerView.findInterceptingOnItemTouchListener(Unknown Source:22)
	at androidx.recyclerview.widget.RecyclerView.onInterceptTouchEvent(Unknown Source:9)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2652)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.dispatchTouchEvent(Unknown Source:181)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:534)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1925)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4298)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(Unknown Source:2)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:492)
	at android.view.View.dispatchPointerEvent(View.java:14884)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6517)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6318)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5853)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5819)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5984)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5827)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6041)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5800)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5853)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5819)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5827)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5800)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8813)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8729)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8698)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8949)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:266)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:246)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8893)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9035)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:845)
	at android.view.Choreographer.doFrame(Choreographer.java:772)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:355)
	at android.app.ActivityThread.main(ActivityThread.java:8080)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)


```

**Comment by rednotmad** [comment]
Thanks!
