### ISSUE TITLE
[Flac] Manually setting album cover causes Vinyl to crash

### ISSUE THREAD

**Issue by FlowingMercury** [VinylMusicPlayer/VinylMusicPlayer#761]
**Describe the bug**

**To reproduce**
1. Go to any album's tag editor

2. Click on album cover to update the image and click "pick from local storage" and select the album cover

3. Click the save icon in the lower right corner

**Expected behavior**
The selected album cover should be applied

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: Samsung Galaxy S23 ultra
 - Android Version: 13
 - Vinyl Music Player Version: 1.5.2

**Additional context**

App version: 1.5.2
App version code: 181
Android build version: S918USQU1AWF3
Android release version: 13
Android SDK version: 33
Android build ID: TP1A.220624.014.S918USQU1AWF3
Device brand: samsung
Device manufacturer: samsung
Device name: dm3q
Device model: SM-S918U
Device product name: dm3qsqw
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Wed Jul 12 08:53:44 MDT 2023

Stack:
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/imageio/ImageIO;
	at org.jaudiotagger.tag.images.StandardArtwork.getImage(Unknown Source:9)
	at org.jaudiotagger.tag.images.StandardArtwork.setImageFromData(Unknown Source:0)
	at org.jaudiotagger.tag.flac.FlacTag.createField(Unknown Source:35)
	at org.jaudiotagger.tag.flac.FlacTag.setField(Unknown Source:0)
	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$WriteTagsAsyncTask.doInBackground(Unknown Source:336)
	at com.poupa.vinylmusicplayer.ui.activities.tageditor.AbsTagEditorActivity$WriteTagsAsyncTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 4 more
Caused by: java.lang.ClassNotFoundException: javax.imageio.ImageIO
	... 12 more

this also occurs when downloading covers from last.fm

**Comment by soncaokim** [comment]
Duplcate, cannot be solved. See https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/437#issuecomment-833894541
