### ISSUE TITLE
crash deleting played file from current playlist

### ISSUE THREAD

**Issue by bell07** [VinylMusicPlayer/VinylMusicPlayer#778]
**Describe the bug**

**To reproduce**
1. Go to current playlist
2. Move the last played track (-1) to left site for deletion
3. crash

App version: 1.5.2
App version code: 181
Android build version: d03a124391
Android release version: 13
Android SDK version: 33
Android build ID: lineage_sake-userdebug 13 TQ3A.230805.001 d03a124391
Device brand: asus
Device manufacturer: asus
Device name: ASUS_I006D
Device model: ASUS_I006D
Device product name: WW_I006D
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Tue Sep 12 16:40:05 GMT+02:00 2023

Stack:
java.lang.IndexOutOfBoundsException: Index: 49, Size: 49
	at java.util.ArrayList.remove(ArrayList.java:503)
	at com.poupa.vinylmusicplayer.misc.queue.StaticPlayingQueue.remove(Unknown Source:12)
	at com.poupa.vinylmusicplayer.service.MusicService.removeSong(Unknown Source:18)
	at com.poupa.vinylmusicplayer.helper.MusicPlayerRemote.removeFromQueue(Unknown Source:18)
	at com.poupa.vinylmusicplayer.adapter.song.PlayingQueueAdapter$SwipedResultActionRemoveItem.onSlideAnimationEnd(Unknown Source:26)
	at com.h6ah4i.android.widget.advrecyclerview.swipeable.action.SwipeResultAction.slideAnimationEnd(Unknown Source:0)
	at com.h6ah4i.android.widget.advrecyclerview.swipeable.ItemSlidingAnimator$SlidingAnimatorListenerObject.onAnimationEnd(Unknown Source:49)
	at androidx.core.view.ViewPropertyAnimatorCompat$1.onAnimationEnd(Unknown Source:4)
	at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1115)
	at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:600)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1333)
	at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1575)
	at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:328)
	at android.animation.AnimationHandler.-$$Nest$mdoAnimationFrame(Unknown Source:0)
	at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:86)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:827)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by soncaokim** [comment]
Unfortunately, I cannot reproduce this problem. 

Is it still crashing? Do you have more information on the circumstance/context of the crash (how the playing queue is created, etc)?

**Comment by bell07** [comment]
The playlist (the queue) is created by adding tracks from dynamic "Not played the last month" playlist.
Then I play the tracks in the queue with random order. 
Played tracks I clearup from the queue manually by swiping right, in bottom up order (by removing the "-1" track).
The crash was appeared by last track, if only "-1" and currently playing "0" in the list.  It was reproduceable, I was not able to remove the one track. Maybe the crash depends on the mp3 file. Solved for me by Clearup whole playlist queue. Currently the issue does not appear. Therefore I watch for the issue.

**Comment by soncaokim** [comment]
Hello,

Is this still a problem with the version 1.6.2?

Thanks

**Comment by bell07** [comment]
The problem still occurs in 1.6.2
If I played a track and try to remove, sometimes Vinyl crashes.
If I restart the app and try again, the track is removed.

**Comment by soncaokim** [comment]
> The playlist (the queue) is created by adding tracks from dynamic "Not played the last month" playlist.
> Then I play the tracks in the queue with random order.
> Played tracks I clearup from the queue manually by swiping right, in bottom up order (by removing the "-1" track).
> The crash was appeared by last track, if only "-1" and currently playing "0" in the list. It was reproduceable, I was not able to remove the one track.

I'm still not able to reproduce this...
