### ISSUE TITLE
Crashes every time

### ISSUE THREAD

**Issue by harrypera** [VinylMusicPlayer/VinylMusicPlayer#784]
**Describe the bug**
App crashes whenever a new song is clicked on from the library to play.
Also, a Java null pointer exception is shown for every song when reloading the library.
Most of my songs are opus files, maybe that plays a role 

**To reproduce**
1. Open Vinyl
2. Click any song in the library
3. App crashes

**Expected behavior**

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**

App version: 1.5.3
App version code: 182
Android build version: 33.0210.0210.314
Android release version: 13
Android SDK version: 33
Android build ID: TKQ1.220807.001.33.0210.0210.314 release-keys
Device brand: asus
Device manufacturer: asus
Device name: ASUS_I006D
Device model: ASUS_I006D
Device product name: EU_I006D
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Wed Oct 11 08:05:48 GMT+02:00 2023

Stack:
java.lang.IllegalArgumentException: com.poupa.vinylmusicplayer: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:409)
	at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:758)
	at android.app.PendingIntent.getForegroundService(PendingIntent.java:750)
	at androidx.core.view.accessibility.a.e(Unknown Source:1)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.buildPendingIntent(Unknown Source:14)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.linkButtons(Unknown Source:42)
	at com.poupa.vinylmusicplayer.appwidgets.AppWidgetClassic.performUpdate(Unknown Source:18)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.notifyChange(Unknown Source:23)
	at com.poupa.vinylmusicplayer.service.MusicService.sendChangeInternal(Unknown Source:15)
	at com.poupa.vinylmusicplayer.service.MusicService.handleAndSendChangeInternal(Unknown Source:3)
	at com.poupa.vinylmusicplayer.service.MusicService.notifyChange(Unknown Source:0)
	at com.poupa.vinylmusicplayer.service.MusicService.openTrackAndPrepareNextAt(Unknown Source:17)
	at com.poupa.vinylmusicplayer.service.MusicService.playSongAtImpl(Unknown Source:0)
	at com.poupa.vinylmusicplayer.service.PlaybackHandler.handleMessage(Unknown Source:182)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:241)
	at android.os.Looper.loop(Looper.java:358)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by soncaokim** [comment]
No, I dont have persistent crashes. I dont have opus tracks though.

The exception message suggests (im)mutable flags - I think this is what
@octoton have done in the merged Android 13 branch.

Sorry I cannot provide any link/ref, I'm only on my phone now.

**Comment by AdrienPoupa** [comment]
I just tried on my Android 13 phone with 1.5.3, works with both MP3 and Opus so it could be specific to some phones or files. I guess it can't hurt to set the flag correctly.

**Comment by AdrienPoupa** [comment]
Can you please test this and let us know if this solves your issue? Thanks! https://github.com/VinylMusicPlayer/VinylMusicPlayer/releases/download/pre-release/vinyl_master_6fac835_231012-1244-ci-release.apk
