### ISSUE TITLE
Getting glide errors since last update

### ISSUE THREAD

**Issue by mikelpr** [VinylMusicPlayer/VinylMusicPlayer#788]
**Describe the bug**
Opening the app, the album art is missing on all albums, and the little rounded square on the bottom left of the screen that Android pops up whenever something is pasted into the clipboard appears, tapping it reveals the following has been copied to the clipboard:

```
org.jaudiotagger.audio.exceptions.CannotReadException: No Reader associated with this extension:opus
	at org.jaudiotagger.audio.AudioFileIO.readFile(Unknown Source:36)
	at org.jaudiotagger.audio.AudioFileIO.read(Unknown Source:4)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadAudioFile(Unknown Source:69)
	at com.poupa.vinylmusicplayer.glide.audiocover.AudioFileCoverFetcher.loadData(Unknown Source:10)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
	at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)
```

**To reproduce**
1. Open the app
2. Go to the albums tab, in case you're not already there

**Expected behavior**
The covers of the albums in my library show up just fine

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: Sony Xperia 1 IV
 - Android Version: 13
 - ROM: Sony stock
 - Vinyl Music Player Version: 1.5.3

**Additional context**
I've not done any system updates so it's not related to the ROM, vinyl worked just fine until days ago and I've used it for a while so it is indeed something new and I guess it's related to the update pushed to Google Play on the 9th of this month 

Also **quite important**, I actually use cover.jpg files per album folder instead of embedded album art in each song

**Comment by soncaokim** [comment]
Hello,

Sorry for that. I've made a change to reveal more exceptions (they was
there but hidden in the log, not shown).

For this case (no opus support in jaudiotagger) there is no immediate
solution. I will make an adjustment to ignore this one.

**Comment by flipMWD** [comment]
Getting the following error after last update (Play Store). Please tell me if I need to create a new issue.

`java.io.IOException: read failed: EIO (I/O error)
	at libcore.io.IoBridge.read(IoBridge.java:614)
	at java.io.FileInputStream.read(FileInputStream.java:328)
	at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:1023)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadAudioFile(Unknown Source:54)
	at com.poupa.vinylmusicplayer.glide.audiocover.AudioFileCoverFetcher.loadData(Unknown Source:10)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
	at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)
Caused by: android.system.ErrnoException: read failed: EIO (I/O error)
	at libcore.io.Linux.readBytes(Native Method)
	at libcore.io.Linux.read(Linux.java:190)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:613)
	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:325)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:613)
	at libcore.io.IoBridge.read(IoBridge.java:604)
	... 13 more
`

**Comment by soncaokim** [comment]
Hi flipMDW,

Please create a new issue. The stack trace doesnt look excatly the same

Thanks

**Comment by soncaokim** [comment]
> Also **quite important**, I actually use cover.jpg files per album folder instead of embedded album art in each song

I've missed this bit. Do you mean that the cover.jpg is not being loaded anymore, or album cover is not working?

**Comment by mikelpr** [comment]
@soncaokim cover.jpg not being loaded! 🥲

**Comment by soncaokim** [comment]
> @soncaokim cover.jpg not being loaded! 🥲

I'm creating a new issue for this

**Comment by soncaokim** [comment]
https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/816

**Comment by soncaokim** [comment]
Hello, I cannot reproduce this with the latest version (1.5.5, submitted to PlayStore).
Tested with a cover.jpg in the album folder.
Do you mind re-checking and report back your observation to the discussion in #816 ?
