### ISSUE TITLE
Crashes when attempting to play music

### ISSUE THREAD

**Issue by Hew-ux** [VinylMusicPlayer/VinylMusicPlayer#789]
**Describe the bug**
When attempting to play music, it does not play the music and also brings up the debug reporter.

**To reproduce**
1. Open the app
2. Attempt to play music in any method
3. See error

**Expected behavior**
The music to play as it used to in the previous version.

**Device info**
App version: 1.5.3
App version code: 182
Android build version: 058b22-123872
Android release version: 12
Android SDK version: 31
Android build ID: S1SUS32.73-112-31-5
Device brand: motorola
Device manufacturer: motorola
Device name: rhodep
Device model: moto g82 5G
Device product name: rhodep_gn
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Fri Oct 13 08:53:57 GMT+11:00 2023

Stack:
```
java.lang.IllegalArgumentException: com.poupa.vinylmusicplayer: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:377)
	at android.app.PendingIntent.buildServicePendingIntent(PendingIntent.java:726)
	at android.app.PendingIntent.getForegroundService(PendingIntent.java:718)
	at androidx.core.view.accessibility.a.e(Unknown Source:1)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.buildPendingIntent(Unknown Source:14)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.linkButtons(Unknown Source:42)
	at com.poupa.vinylmusicplayer.appwidgets.AppWidgetClassic.performUpdate(Unknown Source:18)
	at com.poupa.vinylmusicplayer.appwidgets.base.BaseAppWidget.notifyChange(Unknown Source:23)
	at com.poupa.vinylmusicplayer.service.MusicService.sendChangeInternal(Unknown Source:15)
	at com.poupa.vinylmusicplayer.service.MusicService.handleAndSendChangeInternal(Unknown Source:3)
	at com.poupa.vinylmusicplayer.service.MusicService.notifyChange(Unknown Source:0)
	at com.poupa.vinylmusicplayer.service.MusicService.openTrackAndPrepareNextAt(Unknown Source:17)
	at com.poupa.vinylmusicplayer.service.MusicService.playSongAtImpl(Unknown Source:0)
	at com.poupa.vinylmusicplayer.service.PlaybackHandler.handleMessage(Unknown Source:182)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Additional context**
This problem did not happen in the previous version, which is strange as the changelog for this version said the only thing that changed was the version string number being updated (unless it was two updates released within one night).

The widget I use is completely blank, however it still reacts to taps and results in the same crash when attempting to play any music.

Restarting the phone and replacing the widget does not fix the issue.

Saw there was a similar report at https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/784 however I do not see the Java stuff on screen, so maybe this is a different issue. I have a mixture of mp3, m4a and ogg music files, none work. Also no mention about the widget.

**Comment by AdrienPoupa** [comment]
Can you please test this and let us know if this solves your issue? Thanks! https://github.com/VinylMusicPlayer/VinylMusicPlayer/releases/download/pre-release/vinyl_master_6fac835_231012-1244-ci-release.apk

**Comment by Hew-ux** [comment]
Yeah, works great! Widget and all.

**Comment by soncaokim** [comment]
Thanks for the cooperation. Closing this issue
