### ISSUE TITLE
Exceptions copied to clipboard, crash on play, snackbar white (on dark theme)

### ISSUE THREAD

**Issue by flipMWD** [VinylMusicPlayer/VinylMusicPlayer#794]
**Describe the bug**
Since last update on Wednesday (2023-10-11), version 1.5.3 available on the Play Store, the app crashes when attempting to play music, takes a long time to load album covers (mostly .jpg), constantly try to update the music library (the snackbar is white even though I use dark theme), and is repeatedly coping the exceptions to the clipboard. Most of the problems mentioned in #788 and #789 happened to me, but with different exception messages.

**To reproduce**
1. Start the app.
2. Exceptions are sent to the clipboard.
3. Library starts to update.
4. Playing any song crashed the app.

**Expected behavior**
Behave like previous version, do not rescan the library every time the app is opened. Snackbar should follow phone theme.

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: Motorola Moto G82 5G
 - Android Version: 13
 - ROM: Stock Android
 - Vinyl Music Player Version: 1.5.3

**Additional context**
These are some of the messages copied to the clipboard, There was also one called java.lang.IllegalArgumentException, but I was not able to copy it in time.

```
java.io.IOException: read failed: EIO (I/O error)
	at libcore.io.IoBridge.read(IoBridge.java:614)
	at java.io.FileInputStream.read(FileInputStream.java:328)
	at android.os.ParcelFileDescriptor$AutoCloseInputStream.read(ParcelFileDescriptor.java:1023)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadAudioFile(Unknown Source:54)
	at com.poupa.vinylmusicplayer.glide.audiocover.AudioFileCoverFetcher.loadData(Unknown Source:10)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
	at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)
Caused by: android.system.ErrnoException: read failed: EIO (I/O error)
	at libcore.io.Linux.readBytes(Native Method)
	at libcore.io.Linux.read(Linux.java:190)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:613)
	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:325)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:613)
	at libcore.io.IoBridge.read(IoBridge.java:604)
	... 13 more
```

```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.jaudiotagger.audio.AudioFile com.poupa.vinylmusicplayer.util.AutoDeleteAudioFile.get()' on a null object reference
	at com.poupa.vinylmusicplayer.discog.tagging.TagExtractor.extractTags(Unknown Source:8)
	at com.poupa.vinylmusicplayer.discog.Discography.addSong(Unknown Source:23)
	at com.poupa.vinylmusicplayer.discog.Discography.getOrAddSong(Unknown Source:40)
	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:78)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(Unknown Source:17)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by soncaokim** [comment]
Can you please precise, for the first stack trace, what is the corresponding track type (mp3, mp4, opus, flac, etc)?

**Comment by flipMWD** [comment]
Exclusively .mp3 audio files, and .jpg images for album covers. Also, I removed images from most .mp3 files, there are only a handful with embedded album covers. All artist images were downloaded by the app.
