### ISSUE TITLE
The folder view is not working anymore

### ISSUE THREAD

**Issue by ManuRS** [VinylMusicPlayer/VinylMusicPlayer#806]
**Describe the bug**
The folder view is not working anymore after the last updates 1.5.3 and 1.5.4

**To reproduce**
1. Go to Folders on the lateral menu
2. No music

**Expected behavior**
Folder and music files

**Device info**
 - Device: OnePlus Nord2 5G
 - Android Version: 13
 - ROM: OxygeOS 13.0
 - Vinyl Music Player Version: 1.5.3 and 1.5.4

**Additional context**
Works perfectly before the updates. I also deleted the cache in 1.5.4 and the error still.

**Comment by khimaros** [comment]
also running to this with CalyxOS 4.14.0 (Android 13, Pixel 6):

```
No Reader associated with this extension: opus at org.jaudiotagger.audio.AudioFileIO.readFile
```

**Comment by soncaokim** [comment]
Hello,

Can you please try to simulate a song delete:
- go to Library view
- choose a song, three dots menu on the right, then delete
- a wizard should pops up to guide you a permission granting process on a folder. Please select the folder containing your music, and grant the access.
- a pop up open to ask you to confirm the deletion, deny it (we just want to go through the previous permission step)

Then go back to the Folders view. Is the folder navigation becomes functional?

**Comment by ildar** [comment]
I did it and it crashed:

App version: 1.5.3
App version code: 182
Android build version: eng.crossg.20230814.203731
Android release version: 13
Android SDK version: 33
Android build ID: lineage_gsi_arm64_vS-userdebug 13 TQ3A.230805.001
eng.crossg.20230814.203731 test-keys
Device brand: Android
Device manufacturer: unknown
Device name: lineage_gsi_arm64
Device model: LineageOS GSI on ARM64
Device product name: lineage_gsi_arm64_vS
Device hardware name: mt6762
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Sun Oct 15 01:33:16 GMT+06:00 2023

Stack:
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null,
request=995667912, result=-1, data=null} to activity
{com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.AlbumDetailActivity}:
android.content.ActivityNotFoundException: No Activity found to handle
Intent { act=android.intent.action.OPEN_DOCUMENT_TREE
cat=[android.intent.category.OPENABLE] (has extras) }
at android.app.ActivityThread.deliverResults(ActivityThread.java:5339)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:5378)
at
android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
at
android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
at
android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
at
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7924)
at java.lang.reflect.Method.invoke(Native Method)
at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: android.content.ActivityNotFoundException: No Activity found to
handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE
cat=[android.intent.category.OPENABLE] (has extras) }
at
android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2204)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1843)
at android.app.Activity.startActivityForResult(Activity.java:5507)
at androidx.activity.ComponentActivity.startActivityForResult(Unknown
Source:0)
at
androidx.core.app.ActivityCompat$Api16Impl.startActivityForResult(Unknown
Source:0)
at androidx.core.app.ActivityCompat.startActivityForResult(Unknown Source:0)
at androidx.activity.ComponentActivity$2.onLaunch(Unknown Source:167)
at androidx.activity.result.ActivityResultRegistry$2.launch(Unknown
Source:31)
at androidx.fragment.app.Fragment$10.launch(Unknown Source:10)
at androidx.activity.result.ActivityResultLauncher.launch(Unknown Source:1)
at
com.poupa.vinylmusicplayer.dialogs.helper.DeleteSongsDialogAndroidR.lambda$onCreate$0(Unknown
Source:25)
at
com.poupa.vinylmusicplayer.dialogs.helper.DeleteSongsDialogAndroidR.a(Unknown
Source:0)
at com.poupa.vinylmusicplayer.dialogs.helper.a.onActivityResult(Unknown
Source:16)
at androidx.activity.result.ActivityResultRegistry.doDispatch(Unknown
Source:22)
at androidx.activity.result.ActivityResultRegistry.dispatchResult(Unknown
Source:24)
at androidx.activity.ComponentActivity.onActivityResult(Unknown Source:2)
at androidx.fragment.app.FragmentActivity.onActivityResult(Unknown Source:5)
at
com.poupa.vinylmusicplayer.ui.activities.AlbumDetailActivity.onActivityResult(Unknown
Source:0)
at android.app.Activity.dispatchActivityResult(Activity.java:8665)
at android.app.ActivityThread.deliverResults(ActivityThread.java:5332)
... 13 more

**Comment by soncaokim** [comment]
Hi @ildar, thanks for testing.
You should use the version 1.5.4 (not 1.5.3). 
Is there a file manager installed on your device (the File app)? This is required to handle the browsing/permission grant UI.

**Comment by ManuRS** [comment]
I tried on 1.5.4 but the problem persists.

Deleting a song from the library works. The app requests permission as expected, you have to grant folder permission using a  file manager. But the folder view on Vinyl still doesn't work. I tried to force close the app and recreate the database but nothing pops on the folder view.

**Comment by soncaokim** [comment]
This is weird. I ve reinstalled the app during the weekend and folder view works.

Thanks for the help.
I will try to have a new look on this.

**Comment by anufrievroman** [comment]
I have exactly the same issue. Folders view no longer shows any files or folders.

**Comment by soncaokim** [comment]
Call for help: Does anyone have a positive experience (i.e. working as expected) concerning the Folders view?

I still cannot reproduce this.

**Comment by khimaros** [comment]
@soncaokim i don't have a working version above 1.5.2 but would be happy to help reproduce the issues i'm seeing. if you'd like to do a video or audio call to walk through it, let me know. otherwise, just let me know here.

so far i notice that people with issues are running the following ROMs:

- OxygenOS 13.0 (Android 13)
- LineageOS (Android 13)
- CalyxOS 4.14.1 (Android 13)

**Comment by KopfKrieg** [comment]
I'm also affected, with both v1.5.3 and v1.5.4 from F-Droid, on my Pixel 6a running stock Android 14. Also tried resetting the app, but the problem persists.

**Comment by BenjaminHae** [comment]
Same here, pixel 7a stock android 14.

My library is empty, folder view as well.

Scanning returns "nothing to scan"

**Comment by khimaros** [comment]
this also broke my partner who is running stock Pixel 6 (Android 14, build: UP1A.231005.007)

they had previously installed from Google Play

downgrading to the F-Droid release 1.5.2 solved for them.

it should be possible to reproduce this using the emulator in Android Studio

**Comment by soncaokim** [comment]
Hi all,

Since I cannot reproduce this, neither on emulator nor on real device, I'm repeating my call for help: 

Does anyone have a **positive** experience (i.e. working as expected) concerning the Folders view with the later version - 1.6.0 on wards? If yes, I'd like to have a view at your settings/device info.

Thanks!

**Comment by khimaros** [comment]
@soncaokim it seems to be working on your device. maybe it's worth comparing your settings to one of the many failure cases active here?

**Comment by soncaokim** [comment]
As I stated before, I've fresh-reinstalled the app and the folder view works. No special tweaks in the settings.
My device info:
```
App version: 1.6.0-cont-integ_3be3944b_231125-1612 CI <-- integration build, containing this PR
App version code: 186
Android build version: a746396ca8
Android release version: 13
Android SDK version: 33
Android build ID: lineage_cheeseburger-userdebug 13 TQ3A.230901.001 a746396ca8
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus5
Device model: ONEPLUS A5000
Device product name: OnePlus5
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]
```

**Comment by ghostsand** [comment]
I also have this issue since a few version back, i think 1.5.3 was the last one working.
I have a s20 fe

I have tried the following:
1. Reinstall app
2. delete all setting and storage
3. the file permission you asked todo the first time.


App version: 1.6.3
App version code: 189
Android build version: G781BXXS8HWJ8
Android release version: 13
Android SDK version: 33
Android build ID: TP1A.220624.014.G781BXXS8HWJ8
Device brand: samsung
Device manufacturer: samsung
Device name: r8q
Device model: SM-G781B
Device product name: r8qxeea
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

**Comment by BenjaminHae** [comment]
I'm now on 1.6.3, cleared cache and app data(after updating), now scanning works again, but folder view is still empty.

**Comment by ManuRS** [comment]
Same here on 1.6.3, the scanning count correctly the number of songs, but the folder view is empty.

**Comment by khimaros** [comment]
this is working for me now

**Comment by ghostsand** [comment]
Just installed the app again and its working again, thanks for the hard work!
