### ISSUE TITLE
Crash, switching back to app after Android Auto

### ISSUE THREAD

**Issue by soncaokim** [VinylMusicPlayer/VinylMusicPlayer#836]
**Describe the bug**
Crash, switching back to app after Android Auto 

**Additional context**
```
App version: 1.5.5-cont-integ_8e758820_231027-1542 CI
App version code: 184
Android build version: 80b935b9cc
Android release version: 13
Android SDK version: 33
Android build ID: lineage_enchilada-userdebug 13 TQ3A.230901.001 80b935b9cc
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus6
Device model: ONEPLUS A6003
Device product name: OnePlus6
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Time: Sat Oct 28 10:38:36 GMT+02:00 2023

Stack:
java.lang.IllegalStateException: Can't access ViewModels from detached fragment
	at androidx.fragment.app.Fragment.getViewModelStore(Unknown Source:35)
	at androidx.loader.app.LoaderManager.getInstance(Unknown Source:5)
	at com.poupa.vinylmusicplayer.ui.fragments.mainactivity.library.pager.PlaylistsFragment.reload(Unknown Source:0)
	at com.poupa.vinylmusicplayer.discog.b.accept(Unknown Source:20)
	at com.poupa.vinylmusicplayer.helper.WeakMethodReference.run(Unknown Source:10)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by soncaokim** [comment]
Duplicate of https://github.com/VinylMusicPlayer/VinylMusicPlayer/issues/837
