### ISSUE TITLE
java.io.IOException messages in clipboard

### ISSUE THREAD

**Issue by pixel2user** [VinylMusicPlayer/VinylMusicPlayer#849]
**Describe the bug**
App versions 1.5.4 ... 1.5.6 polute my Clipboard (GBord) with a lot of error string, when I play a opus music file.

`java.io.IOException: No space left on device
	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:349)
	at java.io.File.createTempFile(File.java:2007)
	at java.io.File.createTempFile(File.java:2053)
	at com.poupa.vinylmusicplayer.util.AutoDeleteTempFile.create(Unknown Source:32)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadAudioFile(Unknown Source:36)
	at com.poupa.vinylmusicplayer.glide.audiocover.AudioFileCoverFetcher.loadData(Unknown Source:10)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
	at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)`
`com.bumptech.glide.load.engine.DecodeJob.run`
`java.lang.Thread.run`
`java.lang.NullPointerException: Attempt to invoke virtual method 'org.jaudiotagger.audio.AudioFile com.poupa.vinylmusicplayer.util.AutoDeleteAudioFile.get()' on a null object reference
	at com.poupa.vinylmusicplayer.util.MusicUtil.getLyrics(Unknown Source:16)
	at com.poupa.vinylmusicplayer.ui.fragments.player.card.CardPlayerFragment$3.doInBackground(Unknown Source:12)
	at com.poupa.vinylmusicplayer.ui.fragments.player.card.CardPlayerFragment$3.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)`

**To reproduce**
1. Play an *.opus music file
2. Check the clipboard of GBoard for new entries

**Expected behavior**
Playback of opus files without error messages in clipboard.

**Device info**
 - Device: Google Pixel 6 Pro 
 - Android Version: 12
 - ROM: Factory (no Custom ROM)
 - Vinyl Music Player Version: 1.5.6
 - >1000 MB free space

**Additional context**
![Screenshot_20231108-230248](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/25106680/7f3fc13b-341c-474d-a50c-92d605748653)

**Comment by soncaokim** [comment]
Oops, sorry. This is me trying to collecting crash info instead of swallowing them silently. 

Apparently it was done too aggressively - I will revise the implem, especially with Opus/Flac cases where we dont have (yet) a good tagging support.

**Comment by developersu** [comment]
I have similar issue but not once playing specific formats. It happens right after application starts. There are multiple 'toasts' appearing with information about text added into the clipboard. 
And text is like:
```
java.io.FileNotFoundException: /storage/emulated/0/Music/Billy/folder.jpg: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:574)
	at java.io.FileInputStream.<init>(FileInputStream.java:160)
	at com.poupa.vinylmusicplayer.glide.audiocover.AbsCoverFetcher.fallback(Unknown Source:25)
	at com.poupa.vinylmusicplayer.glide.audiocover.AbsCoverFetcher.fallback(Unknown Source:5)
	at com.poupa.vinylmusicplayer.glide.audiocover.SongCoverFetcher.loadData(Unknown Source:47)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
	at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8300)
	at libcore.io.IoBridge.open(IoBridge.java:560)
	... 13 more
```

Hope it helps. Thanks for your work!

**Comment by pixel2user** [comment]
@soncaokim Maybe you can add a debug mode toggle in the settings menu for this kind of  "collecting crash info"?

**Comment by fmarois** [comment]
I'm also seeing the behaviour that @soncaokim  mentioned. Here is my clipboard content if it helps.
```
java.lang.NullPointerException: Attempt to invoke interface method 'org.jaudiotagger.tag.images.Artwork org.jaudiotagger.tag.Tag.getFirstArtwork()' on a null object reference
	at com.poupa.vinylmusicplayer.glide.audiocover.SongCoverFetcher.loadData(Unknown Source:22)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
	at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)
```
Running version 1.5.6
Thank you for your work

**Comment by soncaokim** [comment]
Hello, 
The PR #857 should allow you to opt-in for crash collecting, i.e. not spam the clipboard by default.
And the PR #860 attempts to use notification, instead of clipboard, to inform the user about the crash (if enabled).

Thanks for the patience
