### ISSUE TITLE
error message on starting

### ISSUE THREAD

**Issue by jcarterwms** [VinylMusicPlayer/VinylMusicPlayer#855]
java.lang.NullPointerException: Attempt to invoke interface method 'org.jaudiotagger.tag.images.Artwork org.jaudiotagger.tag.Tag.getFirstArtwork()' on a null object reference
	at com.poupa.vinylmusicplayer.glide.audiocover.SongCoverFetcher.loadData(Unknown Source:22)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
	at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)

This message is on the bottom of the app on each bootup. Maybe related to sharing?

**Comment by russianspy1234** [comment]
Same here, not just on opening the app but on every page
