### ISSUE TITLE
Crash when trying to play music

### ISSUE THREAD

**Issue by u6aab** [VinylMusicPlayer/VinylMusicPlayer#873]
**Describe the bug**
The music player crashes when i try to play a song

**To reproduce**
1. Press play on a song
2. Crash

**Expected behavior**
The song should just play without a crash

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

Copied from crash report:
App version: 1.6.0
App version code: 186
Android build version: 23501000
Android release version: 14
Android SDK version: 34
Android build ID: UP1A.231105.003.23501000
Device brand: google
Device manufacturer: Google
Device name: bramble
Device model: Pixel 4a (5G)
Device product name: bramble
Device hardware name: bramble
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

Rom: calyxos

**Additional context**

## Time: 
2023/11/29 20:54:59
## Stack: 
java.lang.UnsupportedOperationException: AudioEffect: invalid parameter operation
	at android.media.audiofx.AudioEffect.checkStatus(AudioEffect.java:1450)
	at android.media.audiofx.DynamicsProcessing.setTwoFloat(DynamicsProcessing.java:2150)
	at android.media.audiofx.DynamicsProcessing.setInputGainbyChannel(DynamicsProcessing.java:1790)
	at android.media.audiofx.DynamicsProcessing.setInputGainAllChannelsTo(DynamicsProcessing.java:1794)
	at androidx.core.widget.b.o(Unknown Source:1)
	at com.poupa.vinylmusicplayer.service.MultiPlayer.updateVolume(Unknown Source:16)
	at com.poupa.vinylmusicplayer.service.MultiPlayer.setReplayGain(Unknown Source:2)
	at com.poupa.vinylmusicplayer.service.MusicService.applyReplayGain(Unknown Source:132)
	at com.poupa.vinylmusicplayer.service.MusicService.handleChangeInternal(Unknown Source:75)
	at com.poupa.vinylmusicplayer.service.MusicService.handleAndSendChangeInternal(Unknown Source:0)
	at com.poupa.vinylmusicplayer.service.MusicService.notifyChange(Unknown Source:0)
	at com.poupa.vinylmusicplayer.service.MusicService.openTrackAndPrepareNextAt(Unknown Source:17)
	at com.poupa.vinylmusicplayer.service.MusicService.playSongAtImpl(Unknown Source:0)
	at com.poupa.vinylmusicplayer.service.PlaybackHandler.handleMessage(Unknown Source:182)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by soncaokim** [comment]
@MageFroh Looks like this is linked to the latest development - Do you have any idea on this?

**Comment by MageFroh** [comment]
Indeed, this looks like it's in an area I've modified recently.

@u6aab - Does this happen only when ReplayGain is enabled in the settings? If so, can you send the ReplayGain values reported by Vinyl in the song details? ("Details" is an option in the 3 dot menu of a song)

**Comment by u6aab** [comment]
replygain is disabled in settings

**Comment by MageFroh** [comment]
Thanks, it sounds like we cannot assume `DynamicsProcessing` is available on recent Android versions then.
I'll open a PR soon to cope with this kind of situation.

**Comment by KrayZeee** [comment]
im running into the same issue and i have a way to reproduce it
this happens when an 3rd party equalizer uses the audiosession. in my case its poweramp equalizer. if i disable the equalizer for vinyl the app works as expected.

replaygain is disabled in my case aswell

<details> 
  <summary>report</summary>
 App version: 1.6.1
App version code: 187
Android build version: 11010374
Android release version: 14
Android SDK version: 34
Android build ID: UD1A.231105.004
Device brand: google
Device manufacturer: Google
Device name: husky
Device model: Pixel 8 Pro
Device product name: husky
Device hardware name: husky
ABIs: [arm64-v8a]
ABIs (32bit): []
ABIs (64bit): [arm64-v8a]

## Time: 
2023/11/29 23:55:01
## Stack: 
java.lang.UnsupportedOperationException: AudioEffect: invalid parameter operation
 at android.media.audiofx.AudioEffect.checkStatus(AudioEffect.java:1450)
 at android.media.audiofx.DynamicsProcessing.setTwoFloat(DynamicsProcessing.java:2150)
 at android.media.audiofx.DynamicsProcessing.setInputGainbyChannel(DynamicsProcessing.java:1790)
 at android.media.audiofx.DynamicsProcessing.setInputGainAllChannelsTo(DynamicsProcessing.java:1794)
 at androidx.core.widget.b.o(Unknown Source:1)
 at com.poupa.vinylmusicplayer.service.MultiPlayer.updateVolume(Unknown Source:16)
 at com.poupa.vinylmusicplayer.service.MultiPlayer.setDuckingFactor(Unknown Source:2)
 at com.poupa.vinylmusicplayer.service.PlaybackHandler.handleMessage(Unknown Source:99)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:205)
 at android.os.Looper.loop(Looper.java:294)
 at android.os.HandlerThread.run(HandlerThread.java:67)

</details>

**Comment by KrayZeee** [comment]
what im wondering tho is, why vinyl is messing with DynamicsProcessing anyway if replaygain is disabled and the internal equalizer isnt used.
i see in the code that when its disabled that it tries to set the volumedifference to 0, but it should not touch it at all.

**Comment by MageFroh** [comment]
The idea is that the user may modify the replay gain setting while playback is happening: we need to set the gain back to 0dB in this case.
We could instead lazily initialise mDynamicProcessing when a real replay gain is being applied, and destroy it if it is later disabled.

**Comment by MageFroh** [comment]
I've installed Poweramp on my phone and reproduced this issue.
With the code in #875, the crash does not happen any more.
