### ISSUE TITLE
OPUS: CannotReadException Nokia G60 5G

### ISSUE THREAD

**Issue by TheAgamer554** [VinylMusicPlayer/VinylMusicPlayer#874]
**Describe the bug**
I don't knlw what happens but i got this notification randomly

**To reproduce**
1. Listen to some music in the background
2. Get notification

**Expected behavior**
No notification

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

App version: 1.6.1
App version code: 187
Android build version: 00WW_2_39A
Android release version: 13
Android SDK version: 33
Android build ID: 00WW_2_390_SP01
Device brand: Nokia
Device manufacturer: HMD Global
Device name: APO_sprout
Device model: Nokia G60 5G
Device product name: Apollo_00EEA
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2023/11/30 09:39:42
## Stack: 
org.jaudiotagger.audio.exceptions.CannotReadException: No Reader associated with this extension:opus
	at org.jaudiotagger.audio.AudioFileIO.readFile(Unknown Source:36)
	at org.jaudiotagger.audio.AudioFileIO.read(Unknown Source:4)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadReadWriteableAudioFile(Unknown Source:70)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadReadOnlyAudioFile(Unknown Source:55)
	at com.poupa.vinylmusicplayer.glide.audiocover.SongCoverFetcher.loadData(Unknown Source:10)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
	at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)

**Comment by soncaokim** [comment]
Should be fixed by #896 . Please reopen this issue if it's not the case.
