### ISSUE TITLE
Regular crashes while application is in background

### ISSUE THREAD

**Issue by Porkepix** [VinylMusicPlayer/VinylMusicPlayer#880]
**Describe the bug**
Regularly I get the crash popup. Vinyl wasn't even launched once since last boot

**Relevant logs**

```
12-06 05:53:37.386 10771 11171 E AndroidRuntime: FATAL EXCEPTION: PlaybackHandler
12-06 05:53:37.386 10771 11171 E AndroidRuntime: Process: com.poupa.vinylmusicplayer, PID: 10771
12-06 05:53:37.386 10771 11171 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int com.poupa.vinylmusicplayer.service.playback.Playback.position()' on a null object reference
12-06 05:53:37.386 10771 11171 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.MusicService.getSongProgressMillis(Unknown Source:3)
12-06 05:53:37.386 10771 11171 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.MusicService.updateMediaSessionPlaybackState(Unknown Source:20)
12-06 05:53:37.386 10771 11171 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.MusicService.handleChangeInternal(Unknown Source:160)
12-06 05:53:37.386 10771 11171 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.MusicService.handleAndSendChangeInternal(Unknown Source:0)
12-06 05:53:37.386 10771 11171 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.MusicService.notifyChange(Unknown Source:0)
12-06 05:53:37.386 10771 11171 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.ThrottledSeekHandler.run(Unknown Source:9)
12-06 05:53:37.386 10771 11171 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
12-06 05:53:37.386 10771 11171 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
12-06 05:53:37.386 10771 11171 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:251)
12-06 05:53:37.386 10771 11171 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Device info**

 - Device: Xperia XZ
 - Android Version: Oreo (8.0)
 - ROM: Stock
 - Vinyl Music Player Version: 1.6.1

EDIT:

Also found this a little bit earlier in logs:
```
12-06 05:53:37.310 10771 10771 W MessageQueue: Handler (android.os.Handler) {7bbe14c} sending message to a Handler on a dead thread
12-06 05:53:37.310 10771 10771 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {7bbe14c} sending message to a Handler on a dead thread
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:638)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:661)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:630)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:600)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.os.Handler.sendMessage(Handler.java:537)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.media.SubtitleController.processOnAnchor(SubtitleController.java:492)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.media.SubtitleController.hide(SubtitleController.java:365)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.media.SubtitleController.reset(SubtitleController.java:305)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.media.MediaPlayer.reset(MediaPlayer.java:2064)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MultiPlayer.stop(Unknown Source:2)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MultiPlayer.release(Unknown Source:0)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MusicService.releaseResources(Unknown Source:24)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MusicService.onDestroy(Unknown Source:32)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:3574)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.app.ActivityThread.-wrap26(Unknown Source:0)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1708)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.os.Looper.loop(Looper.java:251)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.app.ActivityThread.main(ActivityThread.java:6572)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at java.lang.reflect.Method.invoke(Native Method)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
12-06 05:53:37.310 10771 10771 W MessageQueue: Handler (android.os.Handler) {7bbe14c} sending message to a Handler on a dead thread
12-06 05:53:37.310 10771 10771 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {7bbe14c} sending message to a Handler on a dead thread
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:638)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:661)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:630)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:600)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.os.Handler.sendMessage(Handler.java:537)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.media.SubtitleController.processOnAnchor(SubtitleController.java:492)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.media.SubtitleController.selectTrack(SubtitleController.java:158)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.media.SubtitleController.reset(SubtitleController.java:306)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.media.MediaPlayer.reset(MediaPlayer.java:2064)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MultiPlayer.stop(Unknown Source:2)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MultiPlayer.release(Unknown Source:0)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MusicService.releaseResources(Unknown Source:24)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MusicService.onDestroy(Unknown Source:32)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:3574)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.app.ActivityThread.-wrap26(Unknown Source:0)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1708)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.os.Looper.loop(Looper.java:251)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at android.app.ActivityThread.main(ActivityThread.java:6572)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at java.lang.reflect.Method.invoke(Native Method)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
12-06 05:53:37.310 10771 10771 W MessageQueue: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by soncaokim** [comment]
Closing this in favor of #884
