### ISSUE TITLE
Regular crashes even with the player not running (Android crash handler)

### ISSUE THREAD

**Issue by Porkepix** [VinylMusicPlayer/VinylMusicPlayer#884]
**Describe the bug**
Regularly, Android crash handler appears for some crashes happening, likely on a service when the player isn't even launched.

**To reproduce**
Just have VinylMusicPlayer installed

**Expected behavior**

**Device info**

 - Device: Xperia XZ
 - Android Version: Oreo (8.0)
 - ROM: Stock
 - Vinyl Music Player Version: 1.6.2

**Additional context**

`adb logcat`:
```
12-10 02:19:30.999  4194  4234 E AndroidRuntime: FATAL EXCEPTION: PlaybackHandler
12-10 02:19:30.999  4194  4234 E AndroidRuntime: Process: com.poupa.vinylmusicplayer, PID: 4194
12-10 02:19:30.999  4194  4234 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int com.poupa.vinylmusicplayer.service.playback.Playback.position()' on a null object reference
12-10 02:19:30.999  4194  4234 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.MusicService.getSongProgressMillis(Unknown Source:3)
12-10 02:19:30.999  4194  4234 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.MusicService.updateMediaSessionPlaybackState(Unknown Source:20)
12-10 02:19:30.999  4194  4234 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.MusicService.handleChangeInternal(Unknown Source:160)
12-10 02:19:30.999  4194  4234 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.MusicService.handleAndSendChangeInternal(Unknown Source:0)
12-10 02:19:30.999  4194  4234 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.MusicService.notifyChange(Unknown Source:0)
12-10 02:19:30.999  4194  4234 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.ThrottledSeekHandler.run(Unknown Source:9)
12-10 02:19:30.999  4194  4234 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
12-10 02:19:30.999  4194  4234 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
12-10 02:19:30.999  4194  4234 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:251)
12-10 02:19:30.999  4194  4234 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-10 02:19:31.006  1431  2545 D ActivityManager: New dropbox entry: com.poupa.vinylmusicplayer, data_app_crash, 49aac7d8-bb5a-49c4-b804-1428475a6472
12-10 02:19:31.031  1431  1483 I ActivityManager: Showing crash dialog for package com.poupa.vinylmusicplayer u0
12-10 02:19:31.078  1431  1482 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{17b39a0 u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{5af91d2 4194 com.poupa.vinylmusicplayer/10370/u0 remote:259f45d}: process gone or crashing
12-10 02:19:31.448  1431 16693 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
12-10 02:19:31.448  1431  1482 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
12-10 02:19:31.449  1431  1482 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.sonyericsson.crashmonitor/.receiver.CrashMonitorServiceBroadcastReceiver
```

EDIT: Also found some other things with `adb logcat *:W`, so some messages can be missing:
```
12-10 02:18:19.883  1295  1329 W MediaPlayer: Use of stream types is deprecated for operations other than volume control
12-10 02:18:19.883  1295  1329 W MediaPlayer: See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
12-10 02:18:19.900  1027  1336 W GenericSource: extractor service cannot make data source
12-10 02:18:19.955  1025 13516 E QCExtractor:  ExtendedExtractor failed to instantiate extractor
12-10 02:18:19.963  1027  1336 E MediaExtractor: Trace connect 0xe833c680 0xe8373d00
12-10 02:18:20.049  1958  1958 W Avrcp   : playState object null, sending STOPPED
12-10 02:18:20.070  1996  1996 W StatusBar: removeNotification for unknown key: 0|com.poupa.vinylmusicplayer|2|null|10370
12-10 02:18:20.217  1295  1295 W MessageQueue: Handler (android.os.Handler) {63b8b08} sending message to a Handler on a dead thread
12-10 02:18:20.217  1295  1295 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {63b8b08} sending message to a Handler on a dead thread
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:638)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:661)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:630)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:600)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.os.Handler.sendMessage(Handler.java:537)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.media.SubtitleController.processOnAnchor(SubtitleController.java:492)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.media.SubtitleController.hide(SubtitleController.java:365)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.media.SubtitleController.reset(SubtitleController.java:305)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.media.MediaPlayer.reset(MediaPlayer.java:2064)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MultiPlayer.stop(Unknown Source:2)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MultiPlayer.release(Unknown Source:0)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MusicService.releaseResources(Unknown Source:24)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MusicService.onDestroy(Unknown Source:32)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:3574)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.app.ActivityThread.-wrap26(Unknown Source:0)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1708)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.os.Looper.loop(Looper.java:251)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at android.app.ActivityThread.main(ActivityThread.java:6572)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at java.lang.reflect.Method.invoke(Native Method)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
12-10 02:18:20.217  1295  1295 W MessageQueue: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
12-10 02:18:20.218  1295  1295 W MessageQueue: Handler (android.os.Handler) {63b8b08} sending message to a Handler on a dead thread
12-10 02:18:20.218  1295  1295 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {63b8b08} sending message to a Handler on a dead thread
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:638)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:661)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:630)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:600)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.os.Handler.sendMessage(Handler.java:537)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.media.SubtitleController.processOnAnchor(SubtitleController.java:492)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.media.SubtitleController.selectTrack(SubtitleController.java:158)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.media.SubtitleController.reset(SubtitleController.java:306)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.media.MediaPlayer.reset(MediaPlayer.java:2064)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MultiPlayer.stop(Unknown Source:2)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MultiPlayer.release(Unknown Source:0)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MusicService.releaseResources(Unknown Source:24)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MusicService.onDestroy(Unknown Source:32)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:3574)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.app.ActivityThread.-wrap26(Unknown Source:0)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1708)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.os.Looper.loop(Looper.java:251)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at android.app.ActivityThread.main(ActivityThread.java:6572)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at java.lang.reflect.Method.invoke(Native Method)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
12-10 02:18:20.218  1295  1295 W MessageQueue: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
12-10 02:18:20.219  1027  1335 W AMessage: failed to post message as target looper for handler 0 is gone.
12-10 02:18:20.246  1295  1329 E AndroidRuntime: FATAL EXCEPTION: PlaybackHandler
12-10 02:18:20.246  1295  1329 E AndroidRuntime: Process: com.poupa.vinylmusicplayer, PID: 1295
12-10 02:18:20.246  1295  1329 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int com.poupa.vinylmusicplayer.service.playback.Playback.position()' on a null object reference
12-10 02:18:20.246  1295  1329 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.MusicService.getSongProgressMillis(Unknown Source:3)
12-10 02:18:20.246  1295  1329 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.MusicService.handleChangeInternal(Unknown Source:169)
12-10 02:18:20.246  1295  1329 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.MusicService.handleAndSendChangeInternal(Unknown Source:0)
12-10 02:18:20.246  1295  1329 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.MusicService.notifyChange(Unknown Source:0)
12-10 02:18:20.246  1295  1329 E AndroidRuntime: 	at com.poupa.vinylmusicplayer.service.ThrottledSeekHandler.run(Unknown Source:9)
12-10 02:18:20.246  1295  1329 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:789)
12-10 02:18:20.246  1295  1329 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:98)
12-10 02:18:20.246  1295  1329 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:251)
12-10 02:18:20.246  1295  1329 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)
12-10 02:18:20.285  1022  1177 W JavaDumper:JavaDumper: Could not init dump dir: Unknown error -95
12-10 02:18:20.285  1022  1177 E JavaDumper:FW:  utils.c(257): mkdir (/data/crashdata) failed. File exists
12-10 02:18:20.305  1022  1177 E JavaDumper:FW:  ramdump_framework.c(340): fp is NULL
12-10 02:18:20.305  1022  1177 E JavaDumper:FW:  ramdump_framework.c(519): Read-only file system
12-10 02:18:20.328  1431  1482 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{a2441d7 u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{9f38b71 1295 com.poupa.vinylmusicplayer/10370/u0 remote:d376518}: process gone or crashing
12-10 02:18:20.444  1022  1177 W JavaDumper:FW:  ramdump_framework.c(1918): crashinfo.done not created
12-10 02:18:20.445  1022  1177 E JavaDumper:FW:  JavaDumper.cpp(261): Failed to remove /mnt/tmp/dropbox.txt:No such file or directory
12-10 02:18:20.647  1018 14308 W AudioFlinger::EffectModule: EffectModule 0xec18e600 destructor called with unreleased interface
12-10 02:18:20.648  1018 14308 W AudioFlinger::EffectHandle: disconnect Effect handle 0xea80fac0 disconnected after thread destruction
12-10 02:18:20.673  1431  2539 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
12-10 02:18:20.675  1431  1482 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
12-10 02:18:20.676  1431  1482 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.sonyericsson.crashmonitor/.receiver.CrashMonitorServiceBroadcastReceiver
12-10 02:18:20.751 22640 32272 W ResourceType: ResTable_typeSpec entry count inconsistent: given 969, previously 1027
12-10 02:18:20.755 22640 32272 W ResourceType: ResTable_typeSpec entry count inconsistent: given 351, previously 2595
```

**Comment by soncaokim** [comment]
Yes I m running an integration build, including this fix, since few days. If you want to give it a try, this should be the pre-release version (available on the front page of this repo).

Will prep a release when time allows

**Comment by soncaokim** [comment]
F-Droid builds the app with their own process and signing keys.

One day we need to support export/import of settings and play history (there is already requests for that)
