### ISSUE TITLE
Keep crashing when I attempt to play music

### ISSUE THREAD

**Issue by MrHarrPrime** [VinylMusicPlayer/VinylMusicPlayer#886]
## Time: 
2023/12/13 16:46:56
## Stack: 
java.lang.UnsupportedOperationException: AudioEffect: invalid parameter operation
	at android.media.audiofx.AudioEffect.checkStatus(AudioEffect.java:1460)
	at android.media.audiofx.DynamicsProcessing.setTwoFloat(DynamicsProcessing.java:2150)
	at android.media.audiofx.DynamicsProcessing.setInputGainbyChannel(DynamicsProcessing.java:1790)
	at android.media.audiofx.DynamicsProcessing.setInputGainAllChannelsTo(DynamicsProcessing.java:1794)
	at androidx.core.widget.b.o(Unknown Source:1)
	at com.poupa.vinylmusicplayer.service.MultiPlayer.updateVolume(Unknown Source:16)
	at com.poupa.vinylmusicplayer.service.MultiPlayer.setReplayGain(Unknown Source:2)
	at com.poupa.vinylmusicplayer.service.MusicService.applyReplayGain(Unknown Source:132)
	at com.poupa.vinylmusicplayer.service.MusicService.handleChangeInternal(Unknown Source:75)
	at com.poupa.vinylmusicplayer.service.MusicService.play(Unknown Source:57)
	at com.poupa.vinylmusicplayer.helper.MusicPlayerRemote.resumePlaying(Unknown Source:4)
	at com.poupa.vinylmusicplayer.helper.PlayPauseButtonOnClickHandler.onClick(Unknown Source:10)
	at android.view.View.performClick(View.java:7792)
	at android.view.View.performClickInternal(View.java:7769)
	at android.view.View.access$3800(View.java:910)
	at android.view.View$PerformClick.run(View.java:30218)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

I was just attempting to use Vinyl as normal. I did update recently.

**Comment by KrayZeee** [comment]
are you using the fdroid version(1.6.1)?  please update to 1.6.2 either through by manually installing the prerelease from here
https://github.com/VinylMusicPlayer/VinylMusicPlayer/releases/tag/pre-release
or using playstore.

**Comment by soncaokim** [comment]
This error should be fixed by #875 (where an external equaliser would be enabled).

I'm closing this, if the issue still exist please reopen. Thanks
