### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by CaKrome** [VinylMusicPlayer/VinylMusicPlayer#893]
**Describe the bug**

**To reproduce**
1. Open app
2. app crashes

**Expected behavior**
App works normally

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: OnePlus 6T
 - Android Version: Android 11
 - ROM: LineageOS 18.1
 - Vinyl Music Player Version: 1.6.2

**Additional context**
```App version: 1.6.2
App version code: 188
Android build version: eng.root.20220403.054414
Android release version: 11
Android SDK version: 30
Android build ID: lineage_fajita-userdebug 11 RQ3A.211001.001 eng.root.20220403.054414 dev-keys
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus6T
Device model: ONEPLUS A6013
Device product name: OnePlus6T
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2023/12/16 19:24:34
## Stack: 
org.jaudiotagger.audio.exceptions.CannotReadException: No Reader associated with this extension:mid
 at org.jaudiotagger.audio.AudioFileIO.readFile(Unknown Source:36)
 at org.jaudiotagger.audio.AudioFileIO.read(Unknown Source:4)
 at com.poupa.vinylmusicplayer.util.SAFUtil.loadReadWriteableAudioFile(Unknown Source:70)
 at com.poupa.vinylmusicplayer.util.SAFUtil.loadReadOnlyAudioFile(Unknown Source:55)
 at com.poupa.vinylmusicplayer.glide.audiocover.SongCoverFetcher.loadData(Unknown Source:10)
 at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
 at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
 at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
 at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
 at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:923)
 at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)
```

**Comment by CaKrome** [comment]
This issue is still present in 1.6.3

**Comment by CaKrome** [comment]
Hi @soncaokim,  even if there is no plan to support .mid file, I would not expect the app to crash. Maybe there could be some exception handling when it comes to unsupported formats?

**Comment by soncaokim** [comment]
Hi,

The app continues to operate normally in this case, without the .mid file,
right?

I assume here the error pops up, since the "crash collection" has been
enabled in the app's Setting page. You can turn off the capture and
reporting feature.

S

**Comment by CaKrome** [comment]
Yes it does work without .mid file. Also turning off capture and report feature removed the crash message.
Thanks for the help.
