### ISSUE TITLE
Song to ringtone crash pixel 5a grapheneOS 

### ISSUE THREAD

**Issue by Ag3nt0rang33** [VinylMusicPlayer/VinylMusicPlayer#903]
App version: 1.6.2
App version code: 188
Android build version: 2023121200
Android release version: 14
Android SDK version: 34
Android build ID: UQ1A.231205.014.2023121200
Device brand: google
Device manufacturer: Google
Device name: barbet
Device model: Pixel 5a
Device product name: barbet
Device hardware name: barbet
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2023/12/25 11:45:38
## Stack: 
android.app.RecoverableSecurityException: com.poupa.vinylmusicplayer has no access to content://media/external/audio/media/1000004246
	at android.app.RecoverableSecurityException$1.createFromParcel(RecoverableSecurityException.java:197)
	at android.app.RecoverableSecurityException$1.createFromParcel(RecoverableSecurityException.java:194)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4890)
	at android.os.Parcel.readParcelable(Parcel.java:4872)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.update(ContentProviderNative.java:685)
	at android.content.ContentResolver.update(ContentResolver.java:2440)
	at android.content.ContentResolver.update(ContentResolver.java:2402)
	at com.poupa.vinylmusicplayer.util.RingtoneManager.setRingtone(Unknown Source:27)
	at com.poupa.vinylmusicplayer.helper.menu.SongMenuHelper.handleMenuClick(Unknown Source:23)
	at com.poupa.vinylmusicplayer.helper.menu.SongMenuHelper$OnClickSongMenu.onMenuItemClick(Unknown Source:10)
	at com.poupa.vinylmusicplayer.adapter.song.ArtistSongAdapter$1.onMenuItemClick(Unknown Source:48)
	at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:109)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1265)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3278)
	at android.widget.AbsListView$3.run(AbsListView.java:4244)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8216)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

**Describe the bug**

**To reproduce**

**Expected behavior**

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**

**Comment by exalented** [comment]
This same issue happens on a Pixel 7 and Pixel 8. This might be a GrapheneOS specific issue, not sure. Mp3, m4a, wav and raw aac all crash Vinyl in the same way. The only format that works is flac. An interesting note is that it doesn't show in the system ringtone list.
