### ISSUE TITLE
Logs reporting sending messages to a dead thread

### ISSUE THREAD

**Issue by Porkepix** [VinylMusicPlayer/VinylMusicPlayer#905]
**Describe the bug**
Logs regularly reports trying to send messages to a dead thread; I believe this to be coming from Vinyl looking at previous messages, even if it doesn't strictly appear in the exception.

This *might* be linked to a notification icon appearing very briefly in the system bar from time to time, disappearing only a couple of seconds after apparition.

Context: vinyl isn't currently playing anything

**To reproduce**
No real STR, Vinyl is just installed.

**Expected behavior**
These messages shouldn't be there, and if related to the notification icon, it shouldn't have this behavior.

**Device info**

 - Device: Xperia XZ
 - Android Version: Oreo (8.0)
 - ROM: Stock ROM
 - Vinyl Music Player Version: 1.6.3

**Additional context**

Logs:
```
12-28 22:40:05.062 22704 22704 D PlaybackService: Service created.
12-28 22:40:05.063  1431  2171 I MediaFocusControl:  AudioFocus  abandonAudioFocus() from uid/pid 10370/22670 clientId=android.media.AudioManager@2b4a204com.poupa.vinylmusicplayer.service.MusicService$1@35e63ed
12-28 22:40:05.065 22670 22670 W MessageQueue: Handler (android.os.Handler) {7f0f222} sending message to a Handler on a dead thread
12-28 22:40:05.065 22670 22670 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {7f0f222} sending message to a Handler on a dead thread
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:638)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:661)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:630)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:600)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.os.Handler.sendMessage(Handler.java:537)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.media.SubtitleController.processOnAnchor(SubtitleController.java:492)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.media.SubtitleController.hide(SubtitleController.java:365)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.media.SubtitleController.reset(SubtitleController.java:305)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.media.MediaPlayer.reset(MediaPlayer.java:2064)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MultiPlayer.stop(Unknown Source:2)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MultiPlayer.release(Unknown Source:0)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MusicService.releaseResources(Unknown Source:24)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MusicService.onDestroy(Unknown Source:32)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:3574)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.app.ActivityThread.-wrap26(Unknown Source:0)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1708)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.os.Looper.loop(Looper.java:251)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.app.ActivityThread.main(ActivityThread.java:6572)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at java.lang.reflect.Method.invoke(Native Method)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
12-28 22:40:05.065 22670 22670 W MessageQueue: Handler (android.os.Handler) {7f0f222} sending message to a Handler on a dead thread
12-28 22:40:05.065 22670 22670 W MessageQueue: java.lang.IllegalStateException: Handler (android.os.Handler) {7f0f222} sending message to a Handler on a dead thread
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:638)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.os.Handler.enqueueMessage(Handler.java:661)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.os.Handler.sendMessageAtTime(Handler.java:630)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.os.Handler.sendMessageDelayed(Handler.java:600)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.os.Handler.sendMessage(Handler.java:537)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.media.SubtitleController.processOnAnchor(SubtitleController.java:492)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.media.SubtitleController.selectTrack(SubtitleController.java:158)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.media.SubtitleController.reset(SubtitleController.java:306)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.media.MediaPlayer.reset(MediaPlayer.java:2064)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MultiPlayer.stop(Unknown Source:2)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MultiPlayer.release(Unknown Source:0)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MusicService.releaseResources(Unknown Source:24)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at com.poupa.vinylmusicplayer.service.MusicService.onDestroy(Unknown Source:32)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:3574)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.app.ActivityThread.-wrap26(Unknown Source:0)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1708)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.os.Looper.loop(Looper.java:251)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at android.app.ActivityThread.main(ActivityThread.java:6572)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at java.lang.reflect.Method.invoke(Native Method)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
12-28 22:40:05.065 22670 22670 W MessageQueue: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by soncaokim** [comment]
Hi,

According to the stack trace, it seems that the issue is in the OS underlying code (SubtileController etc). We dont have any hand on this, sorry

**Comment by soncaokim** [comment]
> But from what I can see, the exception goes through Vinyl's code, right?

Correct. Basically Vinyl says: please `android.media.MediaPlayer.reset`, I'm stopping now.
The OS' implementation of `reset` in turn triggers the error you reported.

**Comment by soncaokim** [comment]
Is the notification appearing/disappearing happens when the app is running
and playing?

In this issue report, we are dealing with app stopping... I dont have any
clue/fact to say that the two issues you mentioned are related.

I'd suggest you to open a new bug report.
