### ISSUE TITLE
Crash upon upgrading to 1.6.3 (No suitable parent found from the given view)

### ISSUE THREAD

**Issue by garrison** [VinylMusicPlayer/VinylMusicPlayer#908]
**Describe the bug**
Unexpected crash

**To reproduce**
1. Click on an artist from home screen.

**Expected behavior**
No crash, see albums by artist.

**Device info**

App version: 1.6.3
App version code: 189
Android build version: 10786265
Android release version: 13
Android SDK version: 33
Android build ID: TQ3A.230805.001.S1
Device brand: google
Device manufacturer: Google
Device name: sunfish
Device model: Pixel 4a
Device product name: sunfish
Device hardware name: sunfish
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2023/12/30 23:38:11
## Stack: 
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=100, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.poupa.vinylmusicplayer/com.poupa.vinylmusicplayer.ui.activities.ArtistDetailActivity}: java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5338)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5377)
	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:67)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.IllegalArgumentException: No suitable parent found from the given view. Please provide a valid view.
	at com.google.android.material.snackbar.Snackbar.makeInternal(Unknown Source:50)
	at com.google.android.material.snackbar.Snackbar.make(SourceFile:3)
	at com.poupa.vinylmusicplayer.ui.activities.base.AbsBaseActivity.onRequestPermissionsResult(Unknown Source:59)
	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8811)
	at android.app.Activity.dispatchActivityResult(Activity.java:8669)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:5331)
	... 13 more

**Comment by garrison** [comment]
If I go to the "songs" tab, I can play any song. But if I go to any other tab, the first thing I click on crashes Vinyl.
