### ISSUE TITLE
playlists inaccessible after update, files still intact

### ISSUE THREAD

**Issue by DannekAnnohen** [VinylMusicPlayer/VinylMusicPlayer#913]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**

**Comment by DannekAnnohen** [comment]
App version: 1.6.3
App version code: 189
Android build version: A715FXXUADWH4
Android release version: 13
Android SDK version: 33
Android build ID: TP1A.220624.014.A715FXXUADWH4
Device brand: samsung
Device manufacturer: samsung
Device name: a71
Device model: SM-A715F
Device product name: a71naeea
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/01/07 02:26:26
## Stack: 
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at com.poupa.vinylmusicplayer.service.MusicService.openQueue(SourceFile:2)
	at com.poupa.vinylmusicplayer.helper.MusicPlayerRemote.openAndShuffleQueue(Unknown Source:13)
	at com.poupa.vinylmusicplayer.ui.activities.PlaylistDetailActivity.onOptionsItemSelected(Unknown Source:16)
	at android.app.Activity.onMenuItemSelected(Activity.java:4532)
	at androidx.activity.ComponentActivity.onMenuItemSelected(Unknown Source:0)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(Unknown Source:0)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(Unknown Source:0)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(Unknown Source:2)
	at androidx.appcompat.app.ToolbarActionBar$2.onMenuItemClick(Unknown Source:5)
	at com.kabouzeid.appthemehelper.util.ToolbarContentTintHelper$ATHOnMenuItemClickListener.onMenuItemClick(Unknown Source:13)
	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Unknown Source:18)
	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(Unknown Source:6)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(Unknown Source:4)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(Unknown Source:14)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(SourceFile:2)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(SourceFile:1)
	at androidx.appcompat.widget.ActionMenuView.invokeItem(Unknown Source:3)
	at androidx.appcompat.view.menu.ActionMenuItemView.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:7892)
	at android.widget.TextView.performClick(TextView.java:16220)
	at android.view.View.performClickInternal(View.java:7869)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30891)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by soncaokim** [comment]
Close as related to #965
