### ISSUE TITLE
Bug on my Xiaomi Note 11 Lite

### ISSUE THREAD

**Issue by fabiocosta0305** [VinylMusicPlayer/VinylMusicPlayer#915]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: 
 - Android Version:
 - ROM:
 - Vinyl Music Player Version:

**Additional context**
App version: 1.6.3
App version code: 189
Android build version: V14.0.11.0.TKOEUXM
Android release version: 13
Android SDK version: 33
Android build ID: TKQ1.220829.002 test-keys
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: lisa
Device model: 2109119DG
Device product name: lisa_eea
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/01/10 22:10:48
## Stack: 
org.jaudiotagger.audio.exceptions.CannotReadVideoException: This file appears to be an Mp4 Video file, video files are not supported 
	at org.jaudiotagger.audio.mp4.Mp4InfoReader.read(Unknown Source:252)
	at org.jaudiotagger.audio.mp4.Mp4FileReader.getEncodingInfo(Unknown Source:2)
	at org.jaudiotagger.audio.generic.AudioFileReader2.read(Unknown Source:96)
	at org.jaudiotagger.audio.AudioFileIO.readFile(Unknown Source:14)
	at org.jaudiotagger.audio.AudioFileIO.read(Unknown Source:4)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadReadWriteableAudioFile(Unknown Source:70)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadReadOnlyAudioFile(Unknown Source:55)
	at com.poupa.vinylmusicplayer.discog.tagging.TagExtractor.extractTags(Unknown Source:4)
	at com.poupa.vinylmusicplayer.discog.Discography.addSong(Unknown Source:23)
	at com.poupa.vinylmusicplayer.discog.Discography.getOrAddSong(Unknown Source:40)
	at com.poupa.vinylmusicplayer.discog.Discography.syncWithMediaStore(Unknown Source:78)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:1)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.doInBackground(SourceFile:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by soncaokim** [comment]
As mentioned in the error message, this appears to be a video. The app tries to scan the file for music tags (artist, title, album, etc) and doesnt support video files.

If this is bugging you too much, you can disable error collecting/reporting via app's Settings page
