### ISSUE TITLE
Background crash on library scan

### ISSUE THREAD

**Issue by nivensd** [VinylMusicPlayer/VinylMusicPlayer#919]
**Describe the bug**
Upon opening Vinyl, when it begins to scan for media files, it has a background crash that doesn't actually crash out the app. It just pops up this crash report as a notification. I can't even find the file listed in the report.

**To reproduce**
Open Vinyl with files on your phone..?

**Expected behavior**
Opening the app without a crash report happening.

**Device info**
App version: 1.6.3
App version code: 189
Android build version: e171d1
Android release version: 11
Android SDK version: 30
Android build ID: RPMS31.Q1-54-13-11
Device brand: motorola
Device manufacturer: motorola
Device name: sofia
Device model: moto g power
Device product name: sofia_retail
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/01/21 20:51:04
## Stack: 
org.jaudiotagger.audio.exceptions.InvalidAudioFrameException: No audio header found within song-175653688310359709494240.mp3
	at org.jaudiotagger.audio.mp3.MP3AudioHeader.<init>(SourceFile:3)
	at org.jaudiotagger.audio.mp3.MP3File.<init>(SourceFile:4)
	at org.jaudiotagger.audio.mp3.MP3FileReader.read(Unknown Source:4)
	at org.jaudiotagger.audio.AudioFileIO.readFile(Unknown Source:14)
	at org.jaudiotagger.audio.AudioFileIO.read(Unknown Source:4)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadReadWriteableAudioFile(Unknown Source:70)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadReadOnlyAudioFile(Unknown Source:55)
	at com.poupa.vinylmusicplayer.glide.audiocover.SongCoverFetcher.loadData(Unknown Source:10)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
	at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)

**Comment by soncaokim** [comment]
Hi, as you noted, this is not a blocking/breaking error. The app failed to scan the ID3 header of one of the .mp3, and reported it. You can disable the exception capture/reporting via the app's setting page.

I'll improve the error reporting though, by providing the original file name (the currently reported name is just that of an internal temporary name).
