### ISSUE TITLE
Crash when saving playlist

### ISSUE THREAD

**Issue by vova7878** [VinylMusicPlayer/VinylMusicPlayer#931]
**Describe the bug**
I'm just trying to save any playlist, but Vinyl is keeps crashing

**Device info**

App version: 1.7.0
App version code: 190
Android build version: eng.blacks.20200101.151935
Android release version: 9
Android SDK version: 28
Android build ID: PQ3A.190801.002
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: nitrogen
Device model: MI MAX 3
Device product name: nitrogen
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/01/31 23:04:35
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: uri
	at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:128)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1276)
	at android.content.ContentResolver.openOutputStream(ContentResolver.java:1056)
	at com.poupa.vinylmusicplayer.util.PlaylistsUtil.savePlaylist(Unknown Source:43)
	at com.poupa.vinylmusicplayer.helper.menu.PlaylistMenuHelper$SavePlaylistAsyncTask.doInBackground(SourceFile:2)
	at com.poupa.vinylmusicplayer.helper.menu.PlaylistMenuHelper$SavePlaylistAsyncTask.doInBackground(SourceFile:1)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by soncaokim** [comment]
Hi

Thanks for reporting this. I assume that the crash happens only on version
1.7.0 of the app, i.e. it worked fine before?

**Comment by vova7878** [comment]
Yes, on some old version (I don’t remember the specific one) it worked fine, but after updating from the play market, all playlists became empty, and new ones were not saved

**Comment by soncaokim** [comment]
I'm going to patch the crash (null pointer), but it will not resolve the root cause, which is still not clear to me.
We havent change this part of playlist save since weeks/months.

A wild guess: Do you have the 'Music' and 'Playlists' folder on your internal storage?

**Comment by vova7878** [comment]
Yes, both folders exist. And music and playlists

**Comment by vova7878** [comment]
>> Are you able and willing to install a devel version of this app
Yes, I can
>> wreck your library
It's already partially ruined....

**Comment by soncaokim** [comment]
> > Are you able and willing to install a devel version of this app
> 
> Yes, I can

The link to the devel version that would fix the issue: https://github.com/VinylMusicPlayer/VinylMusicPlayer/actions/runs/7841900854/artifacts/1232796333

**Comment by vova7878** [comment]
Neither the old nor the new version saves to playlists in the Playlists folder, but the old just crashes, the new is saved into the Music folder

**Comment by soncaokim** [comment]
> the new is saved into the "Music" folder

This is intentional. It's done to align with behaviour starting with Android 13 (where the Playlist folder is not accessible to the app any more)
