### ISSUE TITLE
Crash when selecting a track in a playlist containing duplicates of the same track

### ISSUE THREAD

**Issue by vova7878** [VinylMusicPlayer/VinylMusicPlayer#936]
**Describe the bug**
This issue is related to my previous one.

After a number of reboots, previously empty playlists became full again, but some had duplicate content. When trying to select a track in a large doubled playlist (~300 tracks), two tracks are selected at the same time, but in a small playlist whose entire content fits on the screen (16 tracks) an immediate crash occurs. The "report a crash" button doesn't work, I had to use a third-party logging app

FATAL EXCEPTION: main
Process: com.poupa.vinylmusicplayer, PID: 13857
java.lang.IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:ViewHolder{e8efcfe position=9 id=22516, oldPos=-1, pLpos:-1 not recyclable(1)} 
 View Holder 2:ViewHolder{1679e61 position=1 id=22516, oldPos=-1, pLpos:-1} com.simplecityapps.recyclerview_fastscroll.views.FastScrollRecyclerView{bed8f75 VFED..... ......ID 0,154-1080,1961 #7f09027f app:id/recycler_view}, adapter:com.h6ah4i.android.widget.advrecyclerview.draggable.DraggableItemWrapperAdapter@ccc6160, layout:androidx.recyclerview.widget.LinearLayoutManager@f59eb0a, context:com.poupa.vinylmusicplayer.ui.activities.PlaylistDetailActivity@d8d0e11
	at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(SourceFile:65)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(Unknown Source:109)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(Unknown Source:115)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:20712)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20712)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20712)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20712)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20712)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at com.sothree.slidinguppanel.SlidingUpPanelLayout.onLayout(Unknown Source:145)
	at android.view.View.layout(View.java:20712)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20712)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20712)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20712)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20712)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:753)
	at android.view.View.layout(View.java:20712)
	at android.view.ViewGroup.layout(ViewGroup.java:6194)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2817)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2334)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1481)

**Comment by vova7878** [comment]
![Screenshot_20240202-151602](https://github.com/VinylMusicPlayer/VinylMusicPlayer/assets/46866705/03908cec-0e75-4c7e-bb9f-c232f35b6934)
