### ISSUE TITLE
Crash at start following 1.8.0 update

### ISSUE THREAD

**Issue by Uvik** [VinylMusicPlayer/VinylMusicPlayer#949]
**Issue description**
I just updated Vinyl to version 1.8.0 using F-Droid and the app now crashes upon start.
The view is responsive for one or two seconds, then the crash window pops up.
I can dismiss the crash window and keep browsing through the tabs and lists, but files do not seem to play when I select them. 

**To reproduce**
Start the app.

**Device info and stack trace**
App version: 1.8.0
App version code: 191
Android build version: 2206162227
Android release version: 11
Android SDK version: 30
Android build ID: GM1913_21_220616
Device brand: OnePlus
Device manufacturer: OnePlus
Device name: OnePlus7Pro
Device model: GM1913
Device product name: OnePlus7Pro_EEA
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/02/15 10:13:58
## Stack: 
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$4.done(AsyncTask.java:415)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: Couldn't read row 1052, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
	at android.database.CursorWindow.nativeGetLong(Native Method)
	at android.database.CursorWindow.getLong(CursorWindow.java:542)
	at android.database.AbstractWindowedCursor.getLong(AbstractWindowedCursor.java:77)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.updateExistingRow(Unknown Source:6)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.updateResults(Unknown Source:56)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.<init>(Unknown Source:18)
	at com.poupa.vinylmusicplayer.provider.SongPlayCountStore.getInstance(Unknown Source:13)
	at com.poupa.vinylmusicplayer.loader.TopAndRecentlyPlayedTracksLoader.getTopTracks(Unknown Source:16)
	at com.poupa.vinylmusicplayer.model.smartplaylist.MyTopTracksPlaylist.getSongs(Unknown Source:0)
	at com.poupa.vinylmusicplayer.model.Playlist.getInfoString(Unknown Source:0)
	at com.poupa.vinylmusicplayer.adapter.PlaylistAdapter$1.doInBackground(SourceFile:2)
	at com.poupa.vinylmusicplayer.adapter.PlaylistAdapter$1.doInBackground(SourceFile:1)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more

**Comment by soncaokim** [comment]
Hi, can you please share what was the version of the app before the upgrade to 1.8.0?

Thanks

**Comment by Uvik** [comment]
> Hi, can you please share what was the version of the app before the upgrade to 1.8.0?
> 
> Thanks

Hello! I had no idea how to fetch the info, but I assume I was using version 1.7.0 from F-Droid. 

Anyway, before trying to downgrade, I tried to reinstall the app, and it looks like it starts properly now! I guess something had gone wrong on my setup, and a fresh reinstall cleaned it up. 

Sorry about the disturbance! I will close the issue.
