### ISSUE TITLE
Set ringtone crash

### ISSUE THREAD

**Issue by forMidorii** [VinylMusicPlayer/VinylMusicPlayer#980]
Setting ringtone crash

**To reproduce**
1. Go to '...' songs or any tab like artist
2. Click on '....' any song
3. Scroll down to '....' set as ringtone
5. App version: 1.8.1
App version code: 192
Android build version: S926U1UES1AXBG
Android release version: 14
Android SDK version: 34
Android build ID: UP1A.231005.007.S926U1UES1AXBG
Device brand: samsung
Device manufacturer: samsung
Device name: e2q
Device model: SM-S926U1
Device product name: e2quew
Device hardware name: qcom
ABIs: [arm64-v8a]
ABIs (32bit): []
ABIs (64bit): [arm64-v8a]

## Time: 
2024/03/08 16:59:04
## Stack: 
android.app.RecoverableSecurityException: com.poupa.vinylmusicplayer has no access to content://media/external/audio/media/1000007213
	at android.app.RecoverableSecurityException$1.createFromParcel(RecoverableSecurityException.java:197)
	at android.app.RecoverableSecurityException$1.createFromParcel(RecoverableSecurityException.java:194)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4882)
	at android.os.Parcel.readParcelable(Parcel.java:4864)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3064)
	at android.os.Parcel.createException(Parcel.java:3053)
	at android.os.Parcel.readException(Parcel.java:3036)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.update(ContentProviderNative.java:685)
	at android.content.ContentResolver.update(ContentResolver.java:2416)
	at android.content.ContentResolver.update(ContentResolver.java:2378)
	at com.poupa.vinylmusicplayer.util.RingtoneManager.setRingtone(Unknown Source:27)
	at com.poupa.vinylmusicplayer.helper.menu.SongMenuHelper.handleMenuClick(Unknown Source:23)
	at com.poupa.vinylmusicplayer.helper.menu.SongMenuHelper$OnClickSongMenu.onMenuItemClick(Unknown Source:10)
	at com.poupa.vinylmusicplayer.ui.fragments.player.card.CardPlayerFragment$PortraitImpl$1.onMenuItemClick(Unknown Source:45)
	at android.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:109)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:160)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
	at com.android.internal.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:376)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1362)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3658)
	at android.widget.AbsListView$3.run(AbsListView.java:4844)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

**Expected behavior**
Setting a song (any file format, ex. M4A, MP3, Flac) as personal ringtone 

**Device info**
Please complete the following information. Or if you get directed here from the app, you can paste the collected 
device info.

 - Device: Galaxy s24 plus
 - Android Version: 14
 - ROM: oneui 6.1
 - Vinyl Music Player Version: latest version on Google play 1.8.1

**Additional context**

**Comment by soncaokim** [comment]
Duplicate of #903
