### ISSUE TITLE
AAC file not supported: Crash dump

### ISSUE THREAD

**Issue by keynlotepan** [VinylMusicPlayer/VinylMusicPlayer#985]
App version: 1.8.0
App version code: 191
Android build version: 6c2d01e65b
Android release version: 9
Android SDK version: 28
Android build ID: lineage_tissot-userdebug 9 PQ3A.190801.002 6c2d01e65b
Device brand: Xiaomi
Device manufacturer: Xiaomi
Device name: tissot
Device model: Mi A1
Device product name: lineage_tissot
Device hardware name: qcom
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/03/15 20:13:42
## Extra info: 
Original file: /storage/...
## Stack: 
org.jaudiotagger.audio.exceptions.CannotReadException: No Reader associated with this extension:aac
	at org.jaudiotagger.audio.AudioFileIO.readFile(Unknown Source:36)
	at org.jaudiotagger.audio.AudioFileIO.read(Unknown Source:4)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadReadWriteableAudioFile(Unknown Source:70)
	at com.poupa.vinylmusicplayer.util.SAFUtil.loadReadOnlyAudioFile(Unknown Source:55)
	at com.poupa.vinylmusicplayer.glide.audiocover.SongCoverFetcher.loadData(Unknown Source:10)
	at com.bumptech.glide.load.engine.SourceGenerator.startNextLoad(Unknown Source:15)
	at com.bumptech.glide.load.engine.SourceGenerator.startNext(Unknown Source:97)
	at com.bumptech.glide.load.engine.DecodeJob.runGenerators(Unknown Source:23)
	at com.bumptech.glide.load.engine.DecodeJob.runWrapped(Unknown Source:59)
	at com.bumptech.glide.load.engine.DecodeJob.run(Unknown Source:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
	at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(Unknown Source:31)

**Comment by soncaokim** [comment]
This is due to the fact that we use a library (jaudiotagger) to help parsing embedded artwork. This library does not support AAC files.

I'm gonna stop collecting crash dump in this case, since we cant do much about it

**Comment by soncaokim** [comment]
Closed by #989
