### ISSUE TITLE
App crashs/reboots after opening it for few seconds 

### ISSUE THREAD

**Issue by Nihil901** [VinylMusicPlayer/VinylMusicPlayer#988]
**Describe the bug**
The app crashs or reboots after opening it for 20 to 30 seconds just by doing nothing, even when i don't touch the screen after opening it. 

**To reproduce**
1. Go to 'app'
2. Click on 'anything/nothing'
3. Scroll down 'anywhere'
4. App crashs/reboots after around 20 to 30 seconds 

**Expected behavior**
A smooth experience without crash/reboot

**Device info**
App version: 1.8.2
App version code: 193
Android build version: 2021040000
Android release version: 10
Android SDK version: 29
Android build ID: CPH1823EX_11_F.19
Device manufacturer: OPPO
Device model: CPH1823
Device hardware name: mt6771
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

**More context** 
The duration it takes for the app to crash/restart is nearly the same each time, this is after trying multiple times, i hope this can be helpful.

**Comment by soncaokim** [comment]
Hi, is it possible to enable the "crash report" collection via Settings inside the app? That'll hopefully yield more information on the crash/restart

Thanks

**Comment by soncaokim** [comment]
Hi, is it possible to enable the "crash report" collection via Settings inside the app? That'll hopefully yield more information on the crash/restart

Thanks

**Comment by Nihil901** [comment]
App version: 1.10.0
App version code: 197
Android build version: 2021040000
Android release version: 10
Android SDK version: 29
Android build ID: CPH1823EX_11_F.19
Device brand: OPPO
Device manufacturer: OPPO
Device name: CPH1823
Device model: CPH1823
Device product name: CPH1823
Device hardware name: mt6771
ABIs: [arm64-v8a, armeabi-v7a, armeabi]
ABIs (32bit): [armeabi-v7a, armeabi]
ABIs (64bit): [arm64-v8a]

## Time: 
2024/04/10 19:18:30
## Stack: 
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask$Progress.isEmpty()' on a null object reference
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.onTermination(Unknown Source:13)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.onCancelled(SourceFile:1)
	at com.poupa.vinylmusicplayer.discog.SyncWithMediaStoreAsyncTask.onCancelled(SourceFile:2)
	at android.os.AsyncTask.finish(AsyncTask.java:760)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:779)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7830)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)


---
This is the whole thing
